// @ts-nocheck
import { createHash } from "node:crypto";
import type { ProviderRegistry } from "../../search/provider-registry";
import { providerRegistry as defaultProviders } from "../../search/provider-registry";
import type { SearchResult } from "../../search/types";
import type { Company } from "../model/company";
import type { CompanySignal } from "../model/signal";
import type { RawEvidence, EvidenceRecord } from "../model/evidence";
import type { Job } from "../model/job";
import type { Person, RoleCategory } from "../model/person";
import type { ContactEntry } from "../model/contact";
import { createHeadHunterStores, type HeadHunterStores } from "../stores";
import { resolveCompany, type CompanyCandidate } from "../company/company-resolver";
import { evaluateTriggerQuality, type TriggerQualityStatus } from "./trigger-quality";
import { evaluateEntityRelation, extractCandidateLocation } from "./entity-relation-filter";
import { classifyCantoneseClarity, classifyRa1Clarity } from "../jobs/literal-requirements";
import { resolvePersonCandidate } from "../contacts/person-resolver";
import { discoverContactEntries, type DiscoveredContact } from "../contacts/contact-resolver";
import { ContactSearchBudget } from "../contacts/contact-search-budget";
import { extractOfficialContacts } from "./official-contact-extractor";
import { fetchFirstPartyPage } from "./official-page-fetcher";
import { runHeadhunterRadar } from "./radar-pipeline";
import { buildWeeklySnapshot } from "../reports/weekly-report";
import type { HeadHunterRadarResult } from "./radar-pipeline";
import { generateOpportunityCandidates, type OpportunityCandidate } from "./opportunity-generation";

export type SignalFirstSegment = "hk_finance" | "gba_company" | "outbound_manufacturing";
export interface EventCandidate {
  event_id: string; query: string; title: string; snippet: string; url: string;
  source: string; published_at: string | null; discovered_at: string; target_segment: SignalFirstSegment;
  status: TriggerQualityStatus | "entity_unknown" | "aggregator_only";
  event_date: string | null; company_id: string | null; evidence_id: string | null; reasons: string[];
}
export interface SignalFirstRun {
  run_id: string; started_at: string; finished_at: string; queries: string[]; event_candidates: EventCandidate[];
  opportunities: OpportunityCandidate[];
  eligible_signals: CompanySignal[]; verified_companies: Company[]; deep_dive_companies: string[];
  jobs: Job[]; people: Person[]; contacts: ContactEntry[]; radar: HeadHunterRadarResult;
  snapshot: ReturnType<typeof buildWeeklySnapshot>; provider_usage: ProviderUsage[]; cost: CostSummary;
  regression: RegressionSummary;
}
export interface ProviderUsage { provider: string; request_count: number; success_count: number; failure_count: number; known_cost: number | null; unknown_cost: boolean; }
export interface CostSummary { known_cost: number | null; unknown_cost: boolean; unknown_providers: string[]; cost_per_event_candidate: number | null; cost_per_eligible_signal: number | null; cost_per_contactable_lead: number | null; cost_per_human_approved_a: number | null; }
export interface RegressionSummary { checked: number; contamination: number; freshness_failures: number; tikhub_calls: number; passed: boolean; notes: string[]; }

const EVENT_QUERIES: Array<{ segment: SignalFirstSegment; scope: "mainland" | "hk_global"; queries: string[] }> = [
  { segment: "hk_finance", scope: "hk_global", queries: ["Hong Kong financial company new licence license approval September 2026", "Hong Kong asset manager new fund product expansion September 2026", "Hong Kong bank recruitment day senior appointment 2026", "Hong Kong brokerage wealth institutional expansion office 2026"] },
  { segment: "gba_company", scope: "mainland", queries: ["广州 黄埔 企业 扩产 新项目 2026 9月", "广州 企业 新工厂 新生产线 融资 2026", "黄埔 科学城 企业 投资 项目 招聘 官网", "GBA company international business expansion new project 2026"] },
  { segment: "outbound_manufacturing", scope: "mainland", queries: ["中国 制造企业 泰国 越南 新工厂 投产 2026", "中国 企业 海外 工厂 扩产 招聘 2026", "中国 制造企业 墨西哥 印尼 马来西亚 工厂 项目 2026", "China manufacturer overseas capacity expansion country manager 2026"] },
];
const ACTION = /announce|launch|open|expand|establish|build|invest|hire|recruit|appoint|fund|acqui|merge|license|relocat|restructur|layoff|order|招聘|招募|扩张|宣布|设立|建设|投资|融资|并购|牌照|重组|订单|投产|扩产/i;
const ROLE = /manager|director|head|lead|engineer|finance|hr|human resources|recruit|analyst|compliance|risk|supply chain|country manager|岗位|招聘|人才/i;
const AGGREGATORS = new Set(["linkedin.com", "jobsdb.com", "indeed.com", "glassdoor.com", "michaelpage.com", "robertwalters.com.hk", "randstad.com.hk", "jobstreet.com", "jobs.gov.hk", "efinancialcareers.hk", "scmp.com", "bebee.com"]);
const NON_COMPANY_EVENT_HOST = /(?:^|\.)gov\.(?:hk|cn)|(?:^|\.)gov\.cn$|(?:^|\.)gov\.hk$|(?:^|\.)reuters\.com$|(?:^|\.)bloomberg\.com$|(?:^|\.)hkma\.gov\.hk$/i;

export async function runSignalFirstDiscovery(options: { now?: Date; providers?: ProviderRegistry; stores?: HeadHunterStores; dataDir?: string; runId?: string; maxDeepDiveCompanies?: number; publish?: boolean } = {}): Promise<SignalFirstRun> {
  const now = options.now ?? new Date(); const started = now.toISOString(); const stores = options.stores ?? createHeadHunterStores(options.dataDir); const providers = options.providers ?? defaultProviders;
  const usage = new Map<string, ProviderUsage>(); const candidates: EventCandidate[] = []; const allEvidence: Array<RawEvidence | EvidenceRecord> = await stores.evidence.list(); const evidenceByUrl = new Map(allEvidence.map((e) => [normalizeUrl(e.source_url), e]));
  const search = async (query: string, scope: "mainland" | "hk_global" | "people", segment: SignalFirstSegment | Company["target_segment"], maxResults = 8): Promise<SearchResult[]> => {
    const route = scope === "people" ? ["serper", "exa"] : scope === "mainland" ? ["doubao_search", "serper"] : ["serper", "doubao_search"];
    for (const name of route) { const provider = providers.get(name); if (!provider?.enabled || (provider as { mockMode?: boolean }).mockMode) continue; const stat = usage.get(name) ?? { provider: name, request_count: 0, success_count: 0, failure_count: 0, known_cost: null, unknown_cost: true }; stat.request_count += 1; usage.set(name, stat); try { const results = await provider.search(query, { max_results: maxResults, region: segment === "hk_finance" ? "hk" : "cn" }); stat.success_count += 1; const usable = results.filter((item) => !isSynthetic(item)); if (usable.length) return usable; } catch { stat.failure_count += 1; } }
    return [];
  };
  const saveEvidence = async (result: SearchResult, sourceType: RawEvidence["source_type"] = "search"): Promise<RawEvidence | EvidenceRecord> => { const url = normalizeUrl(result.url); const existing = evidenceByUrl.get(url); if (existing) return existing; const item: EvidenceRecord = { evidence_id: `evidence-${createHash("sha256").update(url).digest("hex").slice(0,24)}`, source_url: url, source_name: result.source_provider, source_type: sourceType, title: result.title, excerpt: result.snippet, raw_title: result.title, raw_excerpt: result.snippet, published_at: result.published_at ?? null, first_seen_at: now.toISOString(), fetched_at: now.toISOString(), observed_at: now.toISOString(), content_hash: createHash("sha256").update(`${result.title}|${result.snippet}`).digest("hex"), immutable: true, human_override: null }; await stores.evidence.insert(item); evidenceByUrl.set(url, item); return item; };
  for (const group of EVENT_QUERIES) for (const query of group.queries) { const results = await search(query, group.scope, group.segment); for (const result of results) { const quality = evaluateTriggerQuality({ ...result, source_type: isLikelyOfficial(result.url) ? "official" : "search" }, { now, max_age_days: 60 }); const host = hostname(result.url); const status = AGGREGATORS.has(host) || NON_COMPANY_EVENT_HOST.test(host) ? "aggregator_only" : quality.status; const evidence = await saveEvidence(result, isLikelyOfficial(result.url) ? "official" : "search"); candidates.push({ event_id: `event-${createHash("sha1").update(`${group.segment}|${normalizeUrl(result.url)}`).digest("hex").slice(0,20)}`, query, title: result.title, snippet: result.snippet, url: normalizeUrl(result.url), source: result.source_provider, published_at: result.published_at ?? null, discovered_at: now.toISOString(), target_segment: group.segment, status, event_date: quality.event_date, company_id: null, evidence_id: "evidence_id" in evidence ? evidence.evidence_id : null, reasons: quality.reasons }); } }
  const uniqueEvents = [...new Map(candidates.map((item) => [item.url, item])).values()]; const companies = await stores.companies.list(); const verified: Company[] = []; const resolutions = [];
  for (const event of uniqueEvents.filter((item) => item.status === "valid_recent_trigger")) { const candidate = candidateFromEvent(event); if (!candidate) { event.status = "entity_unknown"; event.reasons.push("no reliable company identity anchor"); continue; } const resolution = resolveCompany(candidate, companies); resolutions.push(resolution); let company = resolution.company_id ? companies.find((item) => item.company_id === resolution.company_id) : undefined; if (!company && resolution.status === "NEW_COMPANY" && candidate.website) { company = companyFromCandidate(candidate, event.target_segment, now); await stores.companies.upsert(company); companies.push(company); } if (!company || resolution.status === "CONFLICT" || resolution.status === "NEEDS_REVIEW") { event.status = "entity_unknown"; event.reasons.push("company identity requires review"); continue; } event.company_id = company.company_id; if (!verified.some((item) => item.company_id === company!.company_id)) verified.push(company); }
  const eligible: CompanySignal[] = []; const eligibleCompanyIds = new Set<string>();
  for (const event of uniqueEvents.filter((item) => item.company_id && item.status === "valid_recent_trigger")) { const company = verified.find((item) => item.company_id === event.company_id)!; const evidence = evidenceByUrl.get(event.url); const firstParty = isFirstPartyUrl(event.url, company); const independent = uniqueEvents.filter((other) => other.company_id === company.company_id && other.url !== event.url && other.source !== event.source).length > 0; if (!firstParty && !independent) { event.status = "insufficient_event_evidence"; event.reasons.push("requires first-party or two independent sources"); continue; } const signal: CompanySignal = { signal_id: `signal-${createHash("sha1").update(`${company.company_id}|${event.url}`).digest("hex").slice(0,20)}`, company_id: company.company_id, signal_type: classifySignal(`${event.title} ${event.snippet}`), event_date: event.event_date, first_seen_at: now.toISOString(), last_seen_at: now.toISOString(), title: event.title, fact_summary: event.snippet || event.title, inference_summary: null, impact_level: /factory|plant|融资|fund|acquisition|并购|licen|牌照/i.test(`${event.title} ${event.snippet}`) ? "high" : "medium", primary_source_id: evidence && "evidence_id" in evidence ? evidence.evidence_id : null, evidence_ids: evidence && "evidence_id" in evidence ? [evidence.evidence_id] : [], source_confidence: firstParty ? 0.9 : 0.7, created_at: now.toISOString(), updated_at: now.toISOString() }; await stores.signals.upsert(signal); eligible.push(signal); eligibleCompanyIds.add(company.company_id); }
  const deepDiveCompanies = [...eligibleCompanyIds].slice(0, options.maxDeepDiveCompanies ?? 8); const jobs: Job[] = []; const people: Person[] = []; const contacts: ContactEntry[] = [];
  for (const companyId of deepDiveCompanies) { const company = verified.find((item) => item.company_id === companyId)!; const scope = company.target_segment === "hk_finance" ? "hk_global" : "mainland"; const region = company.target_segment === "hk_finance" ? "hk" : "cn"; const jobResults = await search(`${company.name_en ?? company.canonical_name} careers hiring expansion ${company.target_segment === "outbound_manufacturing" ? "factory finance supply chain" : "HR talent acquisition"}`, scope, company.target_segment); for (const result of jobResults.filter((item) => ROLE.test(`${item.title} ${item.snippet}`))) { const relation = evaluateEntityRelation({ target_company: company, candidate: { title: result.title, snippet: result.snippet, url: result.url, location: extractCandidateLocation(result.title, result.snippet) }, candidate_type: "job" }); if (!relation.accepted) continue; const id = `job-${createHash("sha1").update(`${companyId}|${normalizeUrl(result.url)}`).digest("hex").slice(0,20)}`; const job: Job = { job_id: id, company_id: companyId, canonical_title: result.title.slice(0,160), original_titles: [result.title.slice(0,160)], location: extractCandidateLocation(result.title, result.snippet) ?? company.city ?? company.region, role_family: result.title, license_requirement: classifyRa1Clarity(`${result.title} ${result.snippet}`), ra1_clarity: classifyRa1Clarity(`${result.title} ${result.snippet}`), cantonese_clarity: classifyCantoneseClarity(`${result.title} ${result.snippet}`), employment_type: null, first_seen_at: now.toISOString(), last_seen_at: now.toISOString(), current_status: "open", source_urls: [normalizeUrl(result.url)] }; await stores.jobs.upsert(job); jobs.push(job); }
    const peopleResults = await search(`site:linkedin.com/in "${company.name_en ?? company.canonical_name}" Talent Acquisition Recruiter HR Director HRBP`, "people", company.target_segment, 6); for (const result of peopleResults) { const linkedin = linkedinProfile(result.url); if (!linkedin) continue; const text = `${result.title} ${result.snippet}`; const relation = evaluateEntityRelation({ target_company: company, candidate: { title: result.title, snippet: result.snippet, url: result.url }, candidate_type: "person" }); const person = resolvePersonCandidate({ name: result.title.split(/\s[-|–—]\s|\|/)[0]?.trim() || "LinkedIn profile", linkedin_url: linkedin, current_company_id: relation.company_match ? companyId : null, current_title: result.title, role_category: classifyRole(text), source_urls: [normalizeUrl(result.url)] }, companyId); await stores.people.upsert(person); people.push(person); if (person.employment_status === "verified_current") { const contact: ContactEntry = { contact_id: `contact-${person.person_id}`, company_id: companyId, person_id: person.person_id, kind: "linkedin_profile", value: linkedin, label: person.current_title, source_url: result.url, public_verified: true, professional: true, verified_at: now.toISOString(), notes: "公开 LinkedIn 资料" }; await stores.contacts.upsert(contact); contacts.push(contact); } }
    const domain = company.website ? hostname(company.website) : null; if (domain) { const contactResults = await search(`site:${domain} contact recruitment careers`, scope, company.target_segment, 4); const entries: DiscoveredContact[] = []; for (const result of contactResults.filter((item) => hostname(item.url) === domain)) { const fetched = await fetchFirstPartyPage(result.url); const extracted = extractOfficialContacts({ company, source_url: result.url, title: result.title, snippet: result.snippet, inline_content: fetched.content }); entries.push(...(extracted.entries.length ? extracted.entries : [{ type: /career|job/i.test(result.url) ? "careers_entry" : "company_contact_form", value: result.url, source_url: result.url, public_verified: true, professional: true, label: result.title }])); } const discovered = discoverContactEntries({ company_id: companyId, provider: "official_site", entries }, new ContactSearchBudget({ serper: 1, exa: 0, official_site: 1 })); for (const contact of discovered) { await stores.contacts.upsert(contact); contacts.push(contact); } }
  }
  const allSignals = await stores.signals.list(); const allJobs = await stores.jobs.list(); const allPeople = await stores.people.list(); const allContacts = await stores.contacts.list(); const allEvidences = await stores.evidence.list(); const radar = await runHeadhunterRadar({ radar_run_id: options.runId ?? `headhunter-v13-${Date.now()}`, week_key: weekKey(now), companies: verified, signals: allSignals.filter((item) => eligibleCompanyIds.has(item.company_id)), jobs: allJobs.filter((item) => deepDiveCompanies.includes(item.company_id)), people: allPeople.filter((item) => deepDiveCompanies.includes(item.current_company_id ?? "")), contacts: allContacts.filter((item) => deepDiveCompanies.includes(item.company_id)), evidences: allEvidences, trends: [], now }); const snapshot = buildWeeklySnapshot(radar); const opportunities = generateOpportunityCandidates(uniqueEvents, verified, eligible, allContacts, now); const contactable = radar.leads.filter((lead) => lead.contact_gate_status === "pass").length; const providerUsage = [...usage.values()]; const unknownProviders = providerUsage.filter((item) => item.unknown_cost).map((item) => item.provider); const known = providerUsage.every((item) => !item.unknown_cost) ? providerUsage.reduce((sum, item) => sum + (item.known_cost ?? 0), 0) : null; const cost: CostSummary = { known_cost: known, unknown_cost: unknownProviders.length > 0, unknown_providers: unknownProviders, cost_per_event_candidate: known === null || uniqueEvents.length === 0 ? null : known / uniqueEvents.length, cost_per_eligible_signal: known === null || eligible.length === 0 ? null : known / eligible.length, cost_per_contactable_lead: known === null || contactable === 0 ? null : known / contactable, cost_per_human_approved_a: null }; const regression = await runRegression(stores); const finished = new Date().toISOString(); return { run_id: options.runId ?? `headhunter-v13-${Date.now()}`, started_at: started, finished_at: finished, queries: EVENT_QUERIES.flatMap((group) => group.queries), event_candidates: uniqueEvents, eligible_signals: eligible, verified_companies: verified, deep_dive_companies: deepDiveCompanies, jobs, people, contacts, radar, snapshot, opportunities, provider_usage: providerUsage, cost, regression };
}

function candidateFromEvent(event: EventCandidate): CompanyCandidate | null { const domain = registrableDomain(hostname(event.url)); if (!domain || AGGREGATORS.has(domain) || NON_COMPANY_EVENT_HOST.test(hostname(event.url))) return null; const label = domain.split(".")[0].replace(/[-_]+/g, " "); const titlePart = event.title.split(/\s+[|｜–—-]\s+/)[0].replace(/\b(?:official|announcement|news|careers?|jobs?|招聘|官网)\b/gi, "").trim(); if (/年产值|重磅|项目落地|产业项目|签约|investment project|government agreement/i.test(titlePart) && !/[A-Z]{2,}|集团|公司|银行|基金|科技|制造|工业|控股|有限公司/i.test(titlePart)) return null; const name = titlePart.length >= 3 ? titlePart : label; return { input_name: name, name_en: name, website: `https://${domain}`, country: event.target_segment === "hk_finance" ? "Hong Kong" : "China", region: event.target_segment === "hk_finance" ? "Hong Kong" : "GBA", city: event.target_segment === "gba_company" ? "Guangzhou" : null, entity_scope: "operating_entity" }; }
function companyFromCandidate(candidate: CompanyCandidate, segment: SignalFirstSegment, now: Date): Company { const name = candidate.name_en ?? candidate.input_name; const id = `company-${createHash("sha1").update(`${name}|${candidate.website}`).digest("hex").slice(0,20)}`; return { company_id: id, canonical_name: name, name_cn: candidate.name_cn ?? null, name_en: candidate.name_en ?? name, aliases: candidate.aliases ?? [], industry: candidate.industry ?? null, sub_industry: null, country: candidate.country ?? null, region: candidate.region ?? null, city: candidate.city ?? null, company_type: null, website: candidate.website ?? null, linkedin_company_url: candidate.linkedin_company_url ?? null, official_domains: candidate.website ? [hostname(candidate.website)] : [], target_segment: segment, parent_company_id: null, entity_scope: candidate.entity_scope ?? "operating_entity", created_at: now.toISOString(), updated_at: now.toISOString(), last_verified_at: now.toISOString(), status: "active" }; }
async function runRegression(stores: HeadHunterStores): Promise<RegressionSummary> { const companies = await stores.companies.list(); const signals = await stores.signals.list(); const contamination = signals.filter((signal) => /hkex.*express|bankcomm.*bochk|hsbc.*india|protiviti.*india/i.test(`${signal.title} ${signal.fact_summary}`)).length; const freshnessFailures = signals.filter((signal) => signal.event_date === null && /history|careers?|treasury|service/i.test(signal.title)).length; return { checked: Math.min(20, companies.length), contamination, freshness_failures: freshnessFailures, tikhub_calls: 0, passed: contamination === 0 && freshnessFailures === 0, notes: [] }; }
function classifySignal(text: string): CompanySignal["signal_type"] { if (/license|牌照/i.test(text)) return "new_license"; if (/factory|plant|产线|capacity|投产|扩产/i.test(text)) return "factory_expand"; if (/funding|融资|ipo/i.test(text)) return "funding"; if (/acquisition|并购/i.test(text)) return "ma"; if (/hiring|招聘|recruit/i.test(text)) return "hiring"; if (/overseas|海外|新市场/i.test(text)) return "new_market"; return "new_business"; }
function isSynthetic(result: SearchResult): boolean { return /example\.(?:com|org|net|cn)|mock\.chanceping/i.test(result.url); }
function hostname(value: string): string { try { return new URL(value).hostname.replace(/^www\./, "").toLowerCase(); } catch { return ""; } }
function registrableDomain(host: string): string { const parts = host.split("."); return parts.length >= 2 ? parts.slice(-2).join(".") : host; }
function normalizeUrl(value: string): string { try { const url = new URL(value); url.hash = ""; return url.toString().replace(/\/$/, "").toLowerCase(); } catch { return value.trim().toLowerCase().replace(/\/$/, ""); } }
function isLikelyOfficial(url: string): boolean { const host = hostname(url); return Boolean(host) && !AGGREGATORS.has(host) && !/news|media|briefing|press|blog/i.test(host); }
function isFirstPartyUrl(url: string, company: Company): boolean { const host = hostname(url); return [company.website, ...company.official_domains].filter(Boolean).some((item) => host === hostname(item!) || host.endsWith(`.${hostname(item!)}`)); }
function linkedinProfile(url: string): string | null { try { const parsed = new URL(url); if (!/linkedin\.com$/i.test(parsed.hostname.replace(/^www\./, ""))) return null; const match = parsed.pathname.match(/^\/in\/[^/]+/i); return match ? `https://www.linkedin.com${match[0]}` : null; } catch { return null; } }
function classifyRole(text: string): RoleCategory { if (/talent acquisition|recruit|招聘/i.test(text)) return "ta"; if (/hrbp/i.test(text)) return "hrbp"; if (/hr director|人力资源总监/i.test(text)) return "hrd"; if (/country manager/i.test(text)) return "country_manager"; if (/cfo|finance director|财务/i.test(text)) return "finance_leader"; if (/ceo|chief executive/i.test(text)) return "ceo"; if (/coo|chief operating/i.test(text)) return "coo"; if (/business|general manager|总经理/i.test(text)) return "business_leader"; return "other"; }
function weekKey(now: Date): string { const date = new Date(Date.UTC(now.getFullYear(), now.getMonth(), now.getDate())); const day = date.getUTCDay() || 7; date.setUTCDate(date.getUTCDate() + 4 - day); const yearStart = new Date(Date.UTC(date.getUTCFullYear(), 0, 1)); const week = Math.ceil((((date.getTime() - yearStart.getTime()) / 86400000) + 1) / 7); return `${date.getUTCFullYear()}-W${String(week).padStart(2, "0")}`; }
