[Timer]
OnCalendar=
OnBootSec=
OnStartupSec=
OnUnitInactiveSec=
OnActiveSec=
OnUnitActiveSec=
OnUnitActiveSec=72h
Unit=chanceping-opportunity-v2.service
RandomizedDelaySec=0
AccuracySec=1s
Persistent=false
