#!/usr/bin/env bash
# Generated by the control-plane controller template; executed only after exact commit verification.
set -Eeuo pipefail
set -o pipefail
: "${CHANCEPING_DEPLOY_REF:?CHANCEPING_DEPLOY_REF is required}"
: "${CHANCEPING_EXPECTED_COMMIT:?CHANCEPING_EXPECTED_COMMIT is required}"
: "${CHANCEPING_CONTROL_PLANE_COMMIT:?CHANCEPING_CONTROL_PLANE_COMMIT is required}"
export DEPLOY_TAG="$CHANCEPING_DEPLOY_REF"
export EXPECTED_TAG="release-procurement-phase1-2b-20260913-f514ee6"
export EXPECTED_COMMIT="$CHANCEPING_EXPECTED_COMMIT"
export CONTROL_PLANE_COMMIT="$CHANCEPING_CONTROL_PLANE_COMMIT"
export CANARY_ENABLED="${CHANCEPING_PROCUREMENT_CANARY:-1}"
export RUN_REPO_DIR="${CHANCEPING_SERVER_REPO_DIR:-/opt/chanceping}"
if [ "$DEPLOY_TAG" != "$EXPECTED_TAG" ] || [ "$EXPECTED_COMMIT" != "f514ee6b624dc2bb5abf12bb317cb30c37bedb5d" ]; then
  echo "business release tag/commit mismatch" >&2
  exit 2
fi
if ! [[ "$CONTROL_PLANE_COMMIT" =~ ^[0-9a-f]{40}$ ]]; then
  echo "control-plane commit must be a full git SHA" >&2
  exit 2
fi
export BACKUP_ROOT=/var/lib/chanceping/backups/opportunity-v2-phase1-2b-$(date -u +%Y%m%dT%H%M%SZ)
export BACKUP_SOURCE_BACKUP=${BACKUP_ROOT}/sources.json
export BACKUP_POOL_BACKUP=${BACKUP_ROOT}/opportunities.json
export BACKUP_HEALTH_BACKUP=${BACKUP_ROOT}/source-health.json
export BACKUP_SCHEDULER_BACKUP=${BACKUP_ROOT}/scheduler.json
export BACKUP_MANIFEST=${BACKUP_ROOT}/release-manifest.json
export BACKUP_PRE_FLIGHT=${BACKUP_ROOT}/preflight.json
export AUDIT_FILE=${BACKUP_ROOT}/rollout-audit.json
export RELEASE_MANIFEST=${RUN_REPO_DIR}/release-manifest.json
export CURRENT_LINK=${RUN_REPO_DIR}/current
export OP_V2_ROOT=/var/lib/chanceping/opportunity-v2
export SOURCES_PATH=${OP_V2_ROOT}/sources.json
export OPPORTUNITIES_PATH=${OP_V2_ROOT}/opportunities.json
export SOURCE_HEALTH_PATH=${OP_V2_ROOT}/source-health.json
export SCHEDULER_PATH=${OP_V2_ROOT}/scheduler.json
export SERVICE_NAME=chanceping
export TIMER_NAME=chanceping-opportunity-v2.timer
export OP_SERVICE=chanceping-opportunity-v2.service
export BASE_URL=http://127.0.0.1:3000
export QUIESCE_TIMEOUT_SECONDS=90
export CANARY_FAILURE_POLICY=FULL_ROLLBACK
CANARY_SOURCES=(proc-cn-ccgp proc-cn-cib proc-global-ocp proc-eu-ted proc-wb)

mkdir -p "$BACKUP_ROOT"
mkdir -p "$BACKUP_ROOT/.meta"
runtime_before_commit=unknown
previous_release=""
timer_before_enabled=0
timer_before_active=0
op_service_before_active=0
backup_ready=0

write_audit() {
  local status="$1"
  local message="$2"
  ROLLOUT_STATUS="$status"
  cp "$BACKUP_PRE_FLIGHT" "$AUDIT_FILE.pre" 2>/dev/null || true
  cat <<JSON > "$AUDIT_FILE"
  {
    "status": "$status",
    "message": "$message",
    "deployTag": "$DEPLOY_TAG",
    "expectedCommit": "$EXPECTED_COMMIT",
    "controlPlaneCommit": "$CONTROL_PLANE_COMMIT",
    "rolloutStatus": "$ROLLOUT_STATUS",
    "runtimeBeforeCommit": "$runtime_before_commit",
    "previousRelease": "$previous_release",
    "timerEnabledBefore": "$timer_before_enabled",
    "timerActiveBefore": "$timer_before_active",
    "opServiceActiveBefore": "$op_service_before_active",
    "backupRoot": "$BACKUP_ROOT",
    "generatedAt": "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
  }
JSON
}

collect_snapshot() {
  node - <<'NODE'
const fs = require('fs');
const path = process.env.BACKUP_PRE_FLIGHT;
const runtimePath = process.env.SOURCES_PATH;
const poolPath = process.env.OPPORTUNITIES_PATH;
function readSafe(filePath, key) {
  if (!fs.existsSync(filePath)) return { count: 0, ids: [], rows: [] };
  const raw = fs.readFileSync(filePath, 'utf8');
  if (!raw.trim()) return { count: 0, ids: [], rows: [] };
  let parsed;
  try { parsed = JSON.parse(raw); } catch { return { count: 0, ids: [], rows: [] }; }
  const rows = Array.isArray(parsed) ? parsed : (parsed[key] || []);
  const ids = Array.isArray(rows) ? rows.map((row) => row.id).filter(Boolean) : [];
  return {
    count: Array.isArray(rows) ? rows.length : 0,
    ids: ids,
    rows: Array.isArray(rows) ? rows : [],
  };
}
function readPublic(filePath) {
  if (!fs.existsSync(filePath)) return {};
  try { return JSON.parse(fs.readFileSync(filePath, 'utf8')); } catch { return {}; }
}
const sources = readSafe(runtimePath, 'sources');
const pool = readSafe(poolPath, 'opportunities');
const memo = readPublic(`${process.env.BACKUP_ROOT}/public-memo-before.json`);
const radar = readPublic(`${process.env.BACKUP_ROOT}/public-radar-before.json`);
const poolRows = Array.isArray(pool.rows) ? pool.rows : [];
const publicRows = (value) => Array.isArray(value) ? value : Array.isArray(value.items) ? value.items : Array.isArray(value.opportunities) ? value.opportunities : [];
const memoRows = publicRows(memo);
const radarRows = publicRows(radar);
const competitionIds = poolRows.filter((row) => row && row.category === 'competition').map((row) => row.id).filter(Boolean);
const procurementPublicIds = [...memoRows, ...radarRows].filter((row) => row && (row.category === 'procurement_project' || row.procurement)).map((row) => row.id).filter(Boolean);
const loeweRows = poolRows.filter((row) => /loewe/i.test(`${row.title || ''} ${row.source_name || ''}`));
fs.writeFileSync(path, JSON.stringify({ sources, pool, competition_ids: competitionIds, memo_ids: memoRows.map((row) => row.id).filter(Boolean), procurement_public_ids: [...new Set(procurementPublicIds)], loewe: { count: loeweRows.length, ids: loeweRows.map((row) => row.id).filter(Boolean) }, public_snapshot_files: { memo: `${process.env.BACKUP_ROOT}/public-memo-before.json`, radar: `${process.env.BACKUP_ROOT}/public-radar-before.json` } }, null, 2));
NODE
}

capture_postdeploy_public() {
  curl -fsS "$BASE_URL/api/opportunity-v2/radar" > "$BACKUP_ROOT/public-radar-after.json"
  curl -fsS "$BASE_URL/ich/memo" > "$BACKUP_ROOT/public-memo-after.html"
  curl -fsS "$BASE_URL/ich/memo.json" > "$BACKUP_ROOT/public-memo-after.json"
  curl -fsS "$BASE_URL/ich/memo.md" > "$BACKUP_ROOT/public-memo-after.md"
}

compare_public_regression() {
  node - <<'NODE'
const fs = require('fs');
function readJson(filePath) { return JSON.parse(fs.readFileSync(filePath, 'utf8')); }
function rows(value) { return Array.isArray(value) ? value : Array.isArray(value.items) ? value.items : Array.isArray(value.opportunities) ? value.opportunities : []; }
function ids(value) { return [...new Set(rows(value).map((row) => row && row.id).filter(Boolean))]; }
function missing(before, after) { const set = new Set(after); return before.filter((id) => !set.has(id)); }
const before = readJson(process.env.BACKUP_PRE_FLIGHT);
const afterPool = readJson(process.env.OPPORTUNITIES_PATH);
const afterSources = readJson(process.env.SOURCES_PATH);
const afterPoolRows = Array.isArray(afterPool) ? afterPool : (afterPool.opportunities || []);
const afterSourceRows = Array.isArray(afterSources) ? afterSources : (afterSources.sources || []);
const beforeSourceIds = before.sources.ids || [];
const afterSourceIds = afterSourceRows.map((row) => row.id).filter(Boolean);
const afterPoolIds = afterPoolRows.map((row) => row.id).filter(Boolean);
const afterCompetitionIds = afterPoolRows.filter((row) => row && row.category === 'competition').map((row) => row.id).filter(Boolean);
const memoJson = readJson(`${process.env.BACKUP_ROOT}/public-memo-after.json`);
const memoHtml = fs.readFileSync(`${process.env.BACKUP_ROOT}/public-memo-after.html`, 'utf8');
const memoMarkdown = fs.readFileSync(`${process.env.BACKUP_ROOT}/public-memo-after.md`, 'utf8');
const beforeMemoIds = before.memo_ids || [];
const afterMemoIds = ids(memoJson);
const htmlIds = [...memoHtml.matchAll(/data-opportunity-id="([^"]+)"/gu)].map((match) => match[1]);
const markdownIds = [...memoMarkdown.matchAll(/^\|\s*([^|\s]+)\s*\|/gmu)].map((match) => match[1]).filter((id) => id !== 'ID' && id !== '---');
const sameIdSet = (left, right) => JSON.stringify([...new Set(left)].sort()) === JSON.stringify([...new Set(right)].sort());
const sameSequence = (left, right) => left.length === right.length && left.every((id, index) => id === right[index]);
const beforeLoeweIds = before.loewe?.ids || [];
const afterLoeweIds = afterPoolRows.filter((row) => /loewe/i.test(`${row.title || ''} ${row.source_name || ''}`)).map((row) => row.id).filter(Boolean);
const result = { source_membership_loss: missing(beforeSourceIds, afterSourceIds), competition_unexplained_loss: missing(before.competition_ids || [], afterCompetitionIds), memo_unexplained_loss: missing(beforeMemoIds, afterMemoIds), loewe_preserved: beforeLoeweIds.every((id) => afterLoeweIds.includes(id)), loewe_before: beforeLoeweIds, loewe_after: afterLoeweIds, memo_parity: { json_html: htmlIds.length <= afterMemoIds.length && sameSequence(afterMemoIds.slice(0, htmlIds.length), htmlIds), json_markdown: sameIdSet(afterMemoIds, markdownIds), duplicate_ids: afterMemoIds.length - new Set(afterMemoIds).size + htmlIds.length - new Set(htmlIds).size + markdownIds.length - new Set(markdownIds).size, json_count: afterMemoIds.length, html_count: [...new Set(htmlIds)].length, markdown_count: [...new Set(markdownIds)].length }, procurement_public_before: before.procurement_public_ids || [], procurement_public_after: [...new Set(ids(readJson(`${process.env.BACKUP_ROOT}/public-radar-after.json`)))], historical_baseline: 'KNOWN_HISTORICAL_BASELINE_LIMITATION' };
fs.writeFileSync(`${process.env.BACKUP_ROOT}/competition-memo-regression.json`, JSON.stringify(result, null, 2));
if (result.source_membership_loss.length || result.competition_unexplained_loss.length || result.memo_unexplained_loss.length || !result.loewe_preserved || !result.memo_parity.json_html || !result.memo_parity.json_markdown || result.memo_parity.duplicate_ids) throw new Error(`Competition/Memo/LOEWE regression failed: ${JSON.stringify(result)}`);
console.log(JSON.stringify(result));
NODE
}

backup_runtime_file() {
  local source="$1"
  local target="$2"
  if [ -f "$source" ]; then
    cp "$source" "$BACKUP_ROOT/$target"
    sha256sum "$source" > "${BACKUP_ROOT}/$target.sha256"
    stat -c '%n %s %Y' "$source" > "${BACKUP_ROOT}/$target.meta"
    printf '%s\n' EXISTS > "${BACKUP_ROOT}/.meta/$target.state"
  else
    printf '%s\n' ABSENT > "${BACKUP_ROOT}/.meta/$target.state"
  fi
}

restore_runtime_file() {
  local target="$1"
  local source="$2"
  local name="${source##*/}"
  local state_file="${BACKUP_ROOT}/.meta/${name%.sha256}.state"
  if [ -f "$state_file" ] && grep -qx ABSENT "$state_file"; then
    rm -f -- "$target"
  elif [ -f "$source" ]; then
    cp "$source" "$target"
  else
    echo "missing backup for existing runtime file: $target" >&2
    return 1
  fi
}

restore_timer_state() {
  if [ "$timer_before_enabled" = "1" ]; then
    systemctl enable "$TIMER_NAME"
  else
    systemctl disable "$TIMER_NAME"
  fi
  if [ "$timer_before_active" = "1" ]; then
    systemctl start "$TIMER_NAME"
  else
    systemctl stop "$TIMER_NAME"
  fi
}

verify_timer_state() {
  local enabled_now=0
  local active_now=0
  systemctl is-enabled "$TIMER_NAME" --quiet && enabled_now=1 || enabled_now=0
  systemctl is-active "$TIMER_NAME" --quiet && active_now=1 || active_now=0
  if [ "$enabled_now" != "$timer_before_enabled" ]; then
    echo "timer enabled state mismatch: expected=$timer_before_enabled actual=$enabled_now" >&2
    return 1
  fi
  if [ "$active_now" != "$timer_before_active" ]; then
    echo "timer active state mismatch: expected=$timer_before_active actual=$active_now" >&2
    return 1
  fi
}

verify_restored_runtime() {
  local target="$1"
  local name="$2"
  local state_file="${BACKUP_ROOT}/.meta/$name.state"
  if grep -qx ABSENT "$state_file"; then
    [ ! -e "$target" ] || return 1
    return 0
  fi
  [ -f "$target" ] || return 1
  [ -f "${BACKUP_ROOT}/$name.sha256" ] || return 1
  expected_hash="$(awk '{print $1}' "${BACKUP_ROOT}/$name.sha256")"
  actual_hash="$(sha256sum "$target" | awk '{print $1}')"
  [ "$expected_hash" = "$actual_hash" ]
}

verify_all_restored_runtime() {
  verify_restored_runtime "$SOURCES_PATH" sources.json
  verify_restored_runtime "$OPPORTUNITIES_PATH" opportunities.json
  verify_restored_runtime "$SOURCE_HEALTH_PATH" source-health.json
  verify_restored_runtime "$SCHEDULER_PATH" scheduler.json
  verify_restored_runtime "$RELEASE_MANIFEST" release-manifest.json
}

run_http() {
  local url="$1"
  curl -fsS "$url" >/dev/null
}

capture_optional_json() {
  local url="$1"
  local output="$2"
  if ! curl -fsS "$url" > "$output"; then
    # The first procurement rollout may start from a legacy production that
    # does not expose V2 endpoints yet. Keep the pre-deploy regression input
    # valid without weakening the mandatory post-deploy smoke gates.
    printf '%s\n' '{"items":[]}' > "$output"
  fi
}

read_source_state() {
  local source_id="$1"
  (
    export CP_SOURCE_ID="$source_id"
    cd "$CURRENT_LINK"
    "$CURRENT_LINK/node_modules/.bin/tsx" -e 'import { findOpportunityV2Source } from "./src/opportunity-v2"; const source = findOpportunityV2Source(process.env.CP_SOURCE_ID, process.env.SOURCES_PATH); if (!source) { console.error(`Source not found: ${process.env.CP_SOURCE_ID}`); process.exit(2); } console.log(JSON.stringify({ enabled: source.enabled, status: source.status }));'
  )
}

apply_source_state() {
  local source_id="$1"
  local enabled="$2"
  local status="$3"
  (
    export CP_SOURCE_ID="$source_id"
    export CP_ENABLED="$enabled"
    export CP_STATUS="$status"
    cd "$CURRENT_LINK"
    "$CURRENT_LINK/node_modules/.bin/tsx" -e 'import { setOpportunityV2SourceState } from "./src/opportunity-v2"; setOpportunityV2SourceState(process.env.CP_SOURCE_ID, { enabled: process.env.CP_ENABLED === "1", status: process.env.CP_STATUS }, process.env.SOURCES_PATH);'
  )
}

run_direct_source() {
  local source_id="$1"
  (
    export CP_SOURCE_ID="$source_id"
    cd "$CURRENT_LINK"
    "$CURRENT_LINK/node_modules/.bin/tsx" -e 'import { runOpportunityV2Source } from "./src/opportunity-v2"; runOpportunityV2Source({ sourceId: process.env.CP_SOURCE_ID, sourcesPath: process.env.SOURCES_PATH, poolPath: process.env.OPPORTUNITIES_PATH, healthPath: process.env.SOURCE_HEALTH_PATH }).then((result) => console.log(JSON.stringify({ fetched_sources: result.fetched_sources, successful_sources: result.successful_sources, source_health: result.source_health.map((row) => ({ source_id: row.source_id, ok: row.ok, items_seen: row.items_seen })) }))).catch((error) => { console.error(error); process.exit(1); });'
  )
}

checkpoint_canary() {
  local pass_name="$1"
  local source_id="$2"
  local checkpoint="$BACKUP_ROOT/checkpoints/${pass_name}-${source_id}"
  mkdir -p "$checkpoint"
  for runtime_pair in "$SOURCES_PATH sources.json" "$OPPORTUNITIES_PATH opportunities.json" "$SOURCE_HEALTH_PATH source-health.json"; do
    runtime_source="${runtime_pair%% *}"
    runtime_name="${runtime_pair##* }"
    if [ -f "$runtime_source" ]; then
      cp "$runtime_source" "$checkpoint/$runtime_name"
      sha256sum "$runtime_source" > "$checkpoint/$runtime_name.sha256"
      printf '%s\n' EXISTS > "$checkpoint/$runtime_name.state"
    else
      printf '%s\n' ABSENT > "$checkpoint/$runtime_name.state"
    fi
  done
}

run_canary_pass() {
  local pass_name="$1"
  for source_id in "${CANARY_SOURCES[@]}"; do
    checkpoint_canary "$pass_name" "$source_id"
    apply_source_state "$source_id" 1 PENDING
    canary_result="$(run_direct_source "$source_id")" || {
      echo "run canary failed: $pass_name $source_id" >&2
      return 1
    }
    CANARY_RESULT="$canary_result" CP_SOURCE_ID="$source_id" node - <<'NODE'
const result = JSON.parse(process.env.CANARY_RESULT || "");
const health = result.source_health;
if (result.fetched_sources !== 1 || result.successful_sources !== 1 || !Array.isArray(health) || health.length !== 1 || health[0].source_id !== process.env.CP_SOURCE_ID || health[0].ok !== true || health[0].items_seen <= 0) {
  throw new Error(`canary contract failed for ${process.env.CP_SOURCE_ID}: ${JSON.stringify(result)}`);
}
NODE
    apply_source_state "$source_id" 1 ACTIVE
  done
}

assert_ready_core_state() {
  local phase_name="$1"
  (cd "$CURRENT_LINK" && PHASE_NAME="$phase_name" "$CURRENT_LINK/node_modules/.bin/tsx" -e 'import { findOpportunityV2Source, readOpportunityV2Sources } from "./src/opportunity-v2"; const ids = ["proc-cn-ccgp", "proc-cn-cib", "proc-global-ocp", "proc-eu-ted", "proc-wb"]; const sources = readOpportunityV2Sources(process.env.SOURCES_PATH); const states = ids.map((id) => findOpportunityV2Source(id, process.env.SOURCES_PATH)); const missing = ids.filter((id, index) => !states[index]); const enabled = states.filter((source) => source?.enabled === true).length; const active = states.filter((source) => source?.status === "ACTIVE").length; const result = { phase: process.env.PHASE_NAME, registered: ids.length - missing.length, enabled, active, ids }; console.log(JSON.stringify(result)); if (sources.length < ids.length || missing.length || enabled !== ids.length || active !== ids.length) { throw new Error(`READY_CORE state gate failed: ${JSON.stringify(result)}`); }')
}

run_production_quality_gate() {
  local run_name="$1"
  local audit_name="$run_name"
  if [ "$run_name" = "run1" ]; then audit_name=run-1; fi
  if [ "$run_name" = "run2" ]; then audit_name=run-2; fi
  quality_result="$(cd "$CURRENT_LINK" && "$CURRENT_LINK/node_modules/.bin/tsx" -e '
import { hasEncodingCorruption } from '"'"'./src/ich/aggregation/adapters/common'"'"';
import { filterOpportunityV2Radar, hasProcurementDomainTag, isCraftRelevantProcurement, readOpportunityV2Pool, readOpportunityV2Sources } from '"'"'./src/opportunity-v2'"'"';
const now = new Date();
const sources = readOpportunityV2Sources(process.env.SOURCES_PATH);
const pool = readOpportunityV2Pool(process.env.OPPORTUNITIES_PATH);
const publicItems = filterOpportunityV2Radar(pool.opportunities, sources, { category: '"'"'procurement_project'"'"', now });
const itemText = (item) => String(item.title || '"'"''"'"') + '"'"' '"'"' + String(item.summary || '"'"''"'"');
const countryAware = new Set(['"'"'proc-cn-ccgp'"'"', '"'"'proc-cn-cib'"'"', '"'"'proc-eu-ted'"'"', '"'"'proc-wb'"'"']);
const semanticNegative = (text) => /手工(?:外呼|录入|操作|处理|审核|记账|录单)|工艺流程|施工工艺|制造工艺|生产工艺|客服外包|呼叫中心|电话营销|催收服务|软件运维|网络设备/iu.test(text);
const gates = {
  seller_offer_leakage: publicItems.filter((item) => item.procurement?.direction === '"'"'seller_offer'"'"').length,
  awarded_public: publicItems.filter((item) => item.procurement?.stage === '"'"'awarded'"'"').length,
  closed_public: publicItems.filter((item) => item.procurement?.stage === '"'"'closed'"'"').length,
  cancelled_public: publicItems.filter((item) => item.procurement?.stage === '"'"'cancelled'"'"').length,
  construction_only_public: publicItems.filter((item) => /construction|renovation|civil works|建筑工程|工程施工|装修工程/iu.test(itemText(item))).length,
  generic_it_public: publicItems.filter((item) => /software development|software licence|generic IT|服务器|软件系统|网络设备/iu.test(itemText(item))).length,
  unsafe_exact_deadline: publicItems.filter((item) => item.deadline_conflict_unsafe === true && Boolean(item.deadline)).length,
  fake_exact_deadline: publicItems.filter((item) => Boolean(item.deadline) && !item.deadline_source_url).length,
  deadline_source_mismatch: publicItems.filter((item) => Boolean(item.deadline) && Boolean(item.deadline_source_url) && item.deadline_source_url !== item.detail_url && !String(item.deadline_resolution || '"'"''"'"').includes('"'"'cross_source'"'"')).length,
  buyer_label_bleed: publicItems.filter((item) => /(?:采购单位|采购人)\s*[:：]\s*采购单位/iu.test(itemText(item))).length,
  project_id_label_bleed: publicItems.filter((item) => /(?:项目编号|project id)\s*[:：]\s*(?:项目编号|project id)/iu.test(itemText(item))).length,
  procurement_method_label_bleed: publicItems.filter((item) => /(?:采购方式|procurement method)\s*[:：]\s*(?:采购方式|procurement method)/iu.test(itemText(item))).length,
  missing_domain_tag: publicItems.filter((item) => !hasProcurementDomainTag(item.tags)).length,
  procurement_public_with_only_generic_tag: publicItems.filter((item) => item.tags.includes('"'"'procurement'"'"') && !hasProcurementDomainTag(item.tags)).length,
  known_country_as_global: publicItems.filter((item) => countryAware.has(item.source_id) && !item.procurement?.country_code).length,
  aggregator_public_without_official_evidence: publicItems.filter((item) => item.source_id === '"'"'proc-global-ocp'"'"' && (!item.detail_url || item.detail_url.includes('"'"'data.open-contracting.org'"'"'))).length,
  encoding_errors: publicItems.filter((item) => hasEncodingCorruption(item.title) || hasEncodingCorruption(item.summary)).length,
  known_false_positive_call_center: publicItems.filter((item) => /外呼|呼叫中心|电话外拨|机器人呼叫|call\s+center/iu.test(itemText(item))).length,
  manual_operation_keyword_false_positive: publicItems.filter((item) => /手工(?:外呼|录入|操作|处理|审核|记账|录单)/iu.test(itemText(item))).length,
  generic_process_keyword_false_positive: publicItems.filter((item) => /工艺流程|施工工艺|制造工艺|生产工艺/iu.test(itemText(item))).length,
  public_semantic_false_positive: publicItems.filter((item) => !isCraftRelevantProcurement(itemText(item)) || !hasProcurementDomainTag(item.tags) || semanticNegative(itemText(item))).length,
};
console.log(JSON.stringify({ source_count: sources.length, pool_count: pool.opportunities.length, public_procurement: publicItems.length, gates }, null, 2));
')"
  QUALITY_RESULT="$quality_result" RUN_NAME="$audit_name" node - <<'NODE'
const fs = require('fs');
const result = JSON.parse(process.env.QUALITY_RESULT || '{}');
const gates = result.gates || {};
const failed = Object.entries(gates).filter(([, value]) => value !== 0);
fs.writeFileSync(`${process.env.BACKUP_ROOT}/${process.env.RUN_NAME}-quality.json`, JSON.stringify(result, null, 2));
if (failed.length > 0) throw new Error(`production procurement quality gate failed: ${JSON.stringify(Object.fromEntries(failed))}`);
console.log(JSON.stringify({ run: process.env.RUN_NAME, source_count: result.source_count, pool_count: result.pool_count, public_procurement: result.public_procurement, gates }));
NODE
}

cross_source_dedup_audit() {
  (cd "$CURRENT_LINK" && "$CURRENT_LINK/node_modules/.bin/tsx" -e '
import fs from '"'"'node:fs'"'"';
import { deduplicateOpportunityV2, readOpportunityV2Pool } from '"'"'./src/opportunity-v2'"'"';
const pool = readOpportunityV2Pool(process.env.OPPORTUNITIES_PATH);
const required = new Set(['"'"'proc-uk-fts'"'"', '"'"'proc-ca-canadabuys'"'"', '"'"'proc-cn-ccgp'"'"', '"'"'proc-cn-cib'"'"', '"'"'proc-global-ocp'"'"', '"'"'proc-eu-ted'"'"', '"'"'proc-wb'"'"']);
const auditedRows = pool.opportunities.filter((row) => row.category === '"'"'procurement_project'"'"' || required.has(row.source_id) || row.discovered_by_sources.some((sourceId) => required.has(sourceId)));
const deduped = deduplicateOpportunityV2(auditedRows);
const merged = auditedRows.filter((row) => new Set((row.discovered_by_sources || []).filter((sourceId) => required.has(sourceId))).size > 1).map((row) => ({ id: row.id, discovered_by_sources: row.discovered_by_sources }));
const result = { sources_audited: [...new Set([...required, ...auditedRows.map((row) => row.source_id).filter(Boolean)])].sort(), audited_rows: auditedRows.length, duplicate_public_cards: auditedRows.length - deduped.opportunities.length, merged_discovered_by_sources: merged, canonical_duplicate_count: deduped.duplicate_count };
fs.writeFileSync(process.env.BACKUP_ROOT + '"'"'/cross-source-dedup.json'"'"', JSON.stringify(result, null, 2));
console.log(JSON.stringify(result));
if (result.duplicate_public_cards !== 0 || result.canonical_duplicate_count !== 0) throw new Error('"'"'cross-source dedup failed: '"'"' + JSON.stringify(result));
')
}

capture_pool_identities() {
  local run_name="$1"
  RUN_NAME="$run_name" node - <<'NODE'
const fs = require('fs');
const path = process.env.OPPORTUNITIES_PATH;
const parsed = JSON.parse(fs.readFileSync(path, 'utf8'));
const rows = Array.isArray(parsed) ? parsed : (parsed.opportunities || []);
function normalizedUrl(value) {
  if (!value) return '';
  try { const url = new URL(value); url.hash = ''; return `${url.protocol}//${url.host}${url.pathname.replace(/\/+$/u, '')}${url.search}`.toLowerCase(); } catch { return String(value).trim().replace(/\/+$/u, '').toLowerCase(); }
}
function stableKey(row) { return `${row.source_id || ''}|${row.source_item_id || normalizedUrl(row.detail_url) || row.id || ''}`; }
const identities = rows.map((row) => ({ id: row.id, source_id: row.source_id, source_item_id: row.source_item_id || null, detail_url: row.detail_url || null, stable_key: stableKey(row), first_seen_at: row.first_seen_at || null, last_seen_at: row.last_seen_at || null, discovered_by_sources: Array.isArray(row.discovered_by_sources) ? [...row.discovered_by_sources] : [] }));
fs.writeFileSync(`${process.env.BACKUP_ROOT}/${process.env.RUN_NAME}-identities.json`, JSON.stringify({ run: process.env.RUN_NAME, count: identities.length, source_item_ids: identities.map((row) => row.source_item_id).filter(Boolean), identities }, null, 2));
NODE
}

compare_run_idempotency() {
  node - <<'NODE'
const fs = require('fs');
const first = JSON.parse(fs.readFileSync(`${process.env.BACKUP_ROOT}/run_1-identities.json`, 'utf8')).identities || [];
const second = JSON.parse(fs.readFileSync(`${process.env.BACKUP_ROOT}/run_2-identities.json`, 'utf8')).identities || [];
const secondByKey = new Map(second.map((row) => [row.stable_key, row]));
const missingStableIds = first.filter((row) => !secondByKey.has(row.stable_key));
const firstSeenPreserved = first.every((row) => secondByKey.get(row.stable_key)?.first_seen_at === row.first_seen_at);
const lastSeenSafe = first.every((row) => { const next = secondByKey.get(row.stable_key); return !next || !row.last_seen_at || !next.last_seen_at || new Date(next.last_seen_at).getTime() >= new Date(row.last_seen_at).getTime(); });
const discoveredBySourcesMergeSafe = first.every((row) => { const next = secondByKey.get(row.stable_key); const before = new Set(row.discovered_by_sources); return next && [...before].every((sourceId) => next.discovered_by_sources.includes(sourceId)); });
const duplicateOpportunitiesCreated = second.length - new Set(second.map((row) => row.stable_key)).size;
const result = { missing_stable_ids: missingStableIds.map((row) => row.stable_key), duplicate_opportunities_created: duplicateOpportunitiesCreated, same_source_stable_ids: missingStableIds.length === 0, first_seen_at_preserved: firstSeenPreserved, last_seen_at_safe: lastSeenSafe, discovered_by_sources_safe: discoveredBySourcesMergeSafe, discovered_by_sources_merge_safe: discoveredBySourcesMergeSafe };
fs.writeFileSync(`${process.env.BACKUP_ROOT}/run-2-idempotency.json`, JSON.stringify(result, null, 2));
if (missingStableIds.length || duplicateOpportunitiesCreated || !firstSeenPreserved || !lastSeenSafe || !discoveredBySourcesMergeSafe) throw new Error(`run2 idempotency failed: ${JSON.stringify(result)}`);
console.log(JSON.stringify(result));
NODE
}

assert_phase1_stable_state() {
  local phase_name="$1"
  assert_ready_core_state "$phase_name"
  PHASE_NAME="$phase_name" node - <<'NODE'
const fs = require('fs');
const read = (name) => JSON.parse(fs.readFileSync(`${process.env.BACKUP_ROOT}/${name}`, 'utf8'));
const quality = ['run-1-quality.json', 'run-2-quality.json'].map((name) => ({ name, value: read(name) }));
const qualityFailures = quality.flatMap(({ name, value }) => Object.entries(value.gates || {}).filter(([, count]) => count !== 0).map(([gate, count]) => `${name}:${gate}=${count}`));
const idempotency = read('run-2-idempotency.json');
const dedup = read('cross-source-dedup.json');
const regression = read('competition-memo-regression.json');
const result = { phase: process.env.PHASE_NAME, quality_failures: qualityFailures, duplicate_opportunities: idempotency.duplicate_opportunities_created, canonical_duplicates: dedup.canonical_duplicate_count, first_seen_at_preserved: idempotency.first_seen_at_preserved, discovered_by_sources_safe: idempotency.discovered_by_sources_safe, competition_unexplained_loss: regression.competition_unexplained_loss, memo_unexplained_loss: regression.memo_unexplained_loss, memo_parity: regression.memo_parity, loewe_preserved: regression.loewe_preserved };
if (qualityFailures.length || idempotency.duplicate_opportunities_created !== 0 || !idempotency.first_seen_at_preserved || !idempotency.discovered_by_sources_safe || dedup.duplicate_public_cards !== 0 || dedup.canonical_duplicate_count !== 0 || regression.competition_unexplained_loss.length || regression.memo_unexplained_loss.length || !regression.memo_parity.json_html || !regression.memo_parity.json_markdown || regression.memo_parity.duplicate_ids || !regression.loewe_preserved) throw new Error(`final stable gate failed: ${JSON.stringify(result)}`);
console.log(JSON.stringify(result));
NODE
}

rollback() {
  local reason="$1"
  local rollback_failure="rollback failed: $reason"
  local rollback_failed=0
  trap - ERR
  set +e
  if [ "$backup_ready" != "1" ]; then
    rollback_failed=1
  else
    if systemctl is-active "$OP_SERVICE" --quiet; then
      systemctl stop "$OP_SERVICE" || rollback_failed=1
    fi
    restore_runtime_file "$SOURCES_PATH" "$BACKUP_SOURCE_BACKUP" || rollback_failed=1
    restore_runtime_file "$OPPORTUNITIES_PATH" "$BACKUP_POOL_BACKUP" || rollback_failed=1
    restore_runtime_file "$SOURCE_HEALTH_PATH" "$BACKUP_HEALTH_BACKUP" || rollback_failed=1
    restore_runtime_file "$SCHEDULER_PATH" "$BACKUP_SCHEDULER_BACKUP" || rollback_failed=1
    if [ -z "$previous_release" ] || [ ! -d "$previous_release" ]; then
      rollback_failed=1
      rollback_failure="release restore failed"
    else
      ln -sfn "$previous_release" "$CURRENT_LINK" || { rollback_failed=1; rollback_failure="release restore failed"; }
      if [ "$(readlink -f "$CURRENT_LINK")" != "$previous_release" ]; then
        rollback_failed=1
        rollback_failure="release restore failed"
      fi
    fi
    restore_runtime_file "$RELEASE_MANIFEST" "$BACKUP_MANIFEST" || { rollback_failed=1; rollback_failure="release manifest restore failed"; }
    systemctl restart "$SERVICE_NAME" || { rollback_failed=1; rollback_failure="chanceping.service restart failed"; }
    verify_all_restored_runtime || { rollback_failed=1; rollback_failure="restored runtime checksum mismatch"; }
    run_http "$BASE_URL/health" || { rollback_failed=1; rollback_failure="/health verification failed"; }
    run_http "$BASE_URL/ich" || { rollback_failed=1; rollback_failure="/ich verification failed"; }
  fi
  restore_timer_state || { rollback_failed=1; rollback_failure="timer restore failed"; }
  verify_timer_state || { rollback_failed=1; rollback_failure="timer state verification failed"; }
  if [ "$rollback_failed" -ne 0 ]; then
    write_audit ROLLBACK_FAILED "$rollback_failure"
    exit 1
  fi
  write_audit ROLLED_BACK "rollback completed: $reason"
  exit 1
}

trap 'rollback "ERR trap"' ERR

# ----- Phase A: preflight -----
if [ -L "$CURRENT_LINK" ]; then
  previous_release="$(readlink -f "$CURRENT_LINK")"
fi
runtime_before_commit="$(git -C "$RUN_REPO_DIR" rev-parse HEAD)"
systemctl is-enabled "$TIMER_NAME" --quiet && timer_before_enabled=1 || timer_before_enabled=0
systemctl is-active "$TIMER_NAME" --quiet && timer_before_active=1 || timer_before_active=0
systemctl is-active "$OP_SERVICE" --quiet && op_service_before_active=1 || op_service_before_active=0
run_http "$BASE_URL/health"

# ----- Phase B: freeze timer and wait for scheduler quiescence -----
systemctl stop "$TIMER_NAME"
quiesce_deadline=$((SECONDS + QUIESCE_TIMEOUT_SECONDS))
while systemctl is-active "$OP_SERVICE" --quiet; do
  if (( SECONDS >= quiesce_deadline )); then
    echo "scheduler did not become inactive within ${QUIESCE_TIMEOUT_SECONDS}s; stopping rollout before deploy" >&2
    restore_timer_state
    trap - ERR
    exit 1
  fi
  sleep 2
done

# ----- Phase C: runtime backup and read-only snapshot -----
backup_runtime_file "$SOURCES_PATH" sources.json
backup_runtime_file "$OPPORTUNITIES_PATH" opportunities.json
backup_runtime_file "$SOURCE_HEALTH_PATH" source-health.json
backup_runtime_file "$SCHEDULER_PATH" scheduler.json
backup_runtime_file "$RELEASE_MANIFEST" release-manifest.json
backup_ready=1
capture_optional_json "$BASE_URL/api/opportunity-v2/radar" "$BACKUP_ROOT/public-radar-before.json"
capture_optional_json "$BASE_URL/ich/memo.json" "$BACKUP_ROOT/public-memo-before.json"
collect_snapshot
write_audit STAGED "preflight complete"

# ----- Phase C/D: exact target resolved and release deploy -----
git -C "$RUN_REPO_DIR" fetch --no-tags origin "$DEPLOY_TAG"
deploy_commit="$(git -C "$RUN_REPO_DIR" rev-parse --verify 'FETCH_HEAD^{commit}')"
if [ "$deploy_commit" != "$EXPECTED_COMMIT" ]; then
  rollback "deploy commit mismatch: $deploy_commit"
fi
helper=$(mktemp -t chanceping-release-proc-phase1.XXXXXX.sh)
git -C "$RUN_REPO_DIR" show "$deploy_commit:scripts/deploy-release.sh" > "$helper"
chmod 700 "$helper"
CHANCEPING_SERVER_REPO_DIR="$RUN_REPO_DIR" bash "$helper" "$deploy_commit"
rm -f "$helper"

run_http "$BASE_URL/health"
run_http "$BASE_URL/ich"
run_http "$BASE_URL/ich/memo"
run_http "$BASE_URL/ich/memo.json"
run_http "$BASE_URL/ich/memo.md"
run_http "$BASE_URL/api/opportunity-v2/radar"
run_http "$BASE_URL/api/opportunity-v2/sources"
run_http "$BASE_URL/opportunity-v2/admin/sources"

if [ ! -f "$RUN_REPO_DIR/release-manifest.json" ]; then
  rollback "release-manifest missing after deploy"
fi
node - <<'NODE'
const fs = require('fs');
const path = `${process.env.RUN_REPO_DIR}/release-manifest.json`;
const manifest = JSON.parse(fs.readFileSync(path, 'utf8'));
if (!manifest || manifest.commit !== process.env.EXPECTED_COMMIT) {
  process.exit(1);
}
NODE

# ----- Phase F: persistent migration ----
migration_result="$(cd "$CURRENT_LINK" && "$CURRENT_LINK/node_modules/.bin/tsx" -e 'import { DEFAULT_OPPORTUNITY_V2_SOURCES, migrateOpportunityV2Sources } from "./src/opportunity-v2"; const result = migrateOpportunityV2Sources(process.env.SOURCES_PATH); console.log(JSON.stringify({ before_count: result.before_count, after_count: result.after_count, added_ids: result.added_ids, default_source_ids: DEFAULT_OPPORTUNITY_V2_SOURCES.map((source) => source.id) }));')"
MIGRATION_RESULT="$migration_result" node - <<'NODE'
const fs = require('fs');
function readSources(filePath) {
  const parsed = JSON.parse(fs.readFileSync(filePath, 'utf8'));
  const sources = Array.isArray(parsed) ? parsed : parsed.sources;
  if (!Array.isArray(sources)) throw new Error(`invalid source registry: ${filePath}`);
  return sources;
}
const before = readSources(process.env.BACKUP_SOURCE_BACKUP);
const after = readSources(process.env.SOURCES_PATH);
const beforeIds = new Set(before.map((source) => source.id));
const afterIds = new Set(after.map((source) => source.id));
const missing = [...beforeIds].filter((id) => !afterIds.has(id));
const added = [...afterIds].filter((id) => !beforeIds.has(id));
const migration = JSON.parse(process.env.MIGRATION_RESULT || '{}');
const defaultSourceIds = Array.isArray(migration.default_source_ids) ? migration.default_source_ids : [];
const expectedAdded = defaultSourceIds.filter((id) => !beforeIds.has(id));
const unexpectedAdded = added.filter((id) => !defaultSourceIds.includes(id));
if (missing.length > 0) throw new Error(`source membership loss: ${missing.join(', ')}`);
if (unexpectedAdded.length > 0) throw new Error(`unexpected added source ids: ${unexpectedAdded.join(', ')}`);
if (JSON.stringify(added.sort()) !== JSON.stringify(expectedAdded.sort())) throw new Error(`migration added ids mismatch: ${JSON.stringify(added)}`);
for (const id of ['proc-cn-ccgp', 'proc-cn-cib', 'proc-global-ocp', 'proc-eu-ted', 'proc-wb']) {
  const source = after.find((candidate) => candidate.id === id);
  if (!source) throw new Error(`source missing: ${id}`);
  if (source.enabled !== false || source.status !== 'PENDING') throw new Error(`invalid procurement canary state for ${id}`);
}
if (migration.before_count !== before.length || migration.after_count !== after.length) throw new Error('migration report does not match persisted registry');
console.log(JSON.stringify({ before_count: before.length, after_count: after.length, added_ids: added, source_membership_loss: missing, unexpected_added_source_ids: unexpectedAdded }));
NODE

write_audit MIGRATED "source migration applied"

if [ "$CANARY_ENABLED" = "1" ]; then
  run_canary_pass pass1
  assert_ready_core_state run1
  # ----- Run 1 production quality gate -----
  run_production_quality_gate run1
  capture_pool_identities run_1
  run_http "$BASE_URL/api/opportunity-v2/radar"
  run_canary_pass pass2
  assert_ready_core_state run2
  # ----- Run 2 production quality gate -----
  run_production_quality_gate run2
  capture_pool_identities run_2
  compare_run_idempotency
  cross_source_dedup_audit
  capture_postdeploy_public
  compare_public_regression
  assert_phase1_stable_state pre-restore
fi

# ----- restore timer according to original enabled and active states -----
restore_timer_state
verify_timer_state
sleep 1
if systemctl is-active "$OP_SERVICE" --quiet; then
  post_restore_deadline=$((SECONDS + QUIESCE_TIMEOUT_SECONDS))
  while systemctl is-active "$OP_SERVICE" --quiet; do
    if (( SECONDS >= post_restore_deadline )); then
      echo "persistent timer-triggered scheduler did not become inactive" >&2
      false
    fi
    sleep 2
  done
  run_http "$BASE_URL/health"
  run_production_quality_gate post-restore
  capture_postdeploy_public
  compare_public_regression
fi

assert_phase1_stable_state final

trap - ERR
write_audit STABLE "rollout completed"
cat "$AUDIT_FILE"
