import { mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { loadLocalApiEnv } from "../src/config/local-env";

async function main(): Promise<void> {
  const envFile = process.env.CHANCEPING_API_ENV_FILE ?? join(process.env.HOME ?? ".", "Projects/Codex/chanceping/api.env");
  const loaded = loadLocalApiEnv({ enabled: true, envFile });
  if (!loaded.loaded) console.warn(`[V1.3] api.env not loaded: ${loaded.reason}`);
  const { runSignalFirstDiscovery } = await import("../src/headhunter/pipeline/signal-first-discovery");
  process.env.CHANCEPING_HEADHUNTER_DATA_DIR ??= "data/headhunter/v13-signal-first";
  const run = await runSignalFirstDiscovery({ dataDir: process.env.CHANCEPING_HEADHUNTER_DATA_DIR, publish: false });
  const outputDir = join(process.env.CHANCEPING_V13_REPORT_DIR ?? "docs/phase5/v13", run.run_id);
  await mkdir(outputDir, { recursive: true });
  const eventCounts = run.event_candidates.reduce<Record<string, number>>((acc, item) => { acc[item.status] = (acc[item.status] ?? 0) + 1; return acc; }, {});
  const report = `# V1.3 Signal-First Discovery Run\n\n- Run ID: \`${run.run_id}\`\n- Started: ${run.started_at}\n- Finished: ${run.finished_at}\n- Production publish: false\n- TikHub calls: ${run.regression.tikhub_calls}\n\n## Discovery\n\n- Queries: ${run.queries.length}\n- Candidate URLs: ${run.event_candidates.length}\n- Event status: ${JSON.stringify(eventCounts)}\n- Eligible Signals: ${run.eligible_signals.length}\n- Verified Companies: ${run.verified_companies.length}\n- Deep-dive Companies: ${run.deep_dive_companies.length}\n- Jobs: ${run.jobs.length}\n- People: ${run.people.length}\n- Contacts: ${run.contacts.length}\n- Machine A: ${run.radar.leads.filter((lead) => lead.lead_pool === "A_ACTIONABLE").length}\n- B: ${run.radar.leads.filter((lead) => lead.lead_pool === "B_ENRICHMENT").length}\n\n## Precision and safety\n\n- Company identity review: ${run.verified_companies.length}/${run.event_candidates.filter((item) => item.company_id).length || 0} resolved\n- Regression checked: ${run.regression.checked}\n- Severe contamination: ${run.regression.contamination}\n- Freshness failures: ${run.regression.freshness_failures}\n- RA1/Cantonese: enforced by existing literal-only classifiers\n- TikHub: 0\n\n## Cost\n\n- Known cost: ${run.cost.known_cost === null ? "unknown" : `$${run.cost.known_cost.toFixed(4)}`}\n- Unknown providers: ${run.cost.unknown_providers.join(", ") || "none"}\n- Cost / eligible signal: ${run.cost.cost_per_eligible_signal === null ? "unknown" : `$${run.cost.cost_per_eligible_signal.toFixed(4)}`}\n- Cost / contactable lead: ${run.cost.cost_per_contactable_lead === null ? "unknown" : `$${run.cost.cost_per_contactable_lead.toFixed(4)}`}\n\n## Gate\n\nProduction routing remains HOLD. This run is an offline, unpublished candidate run pending human review of all Machine A, at least 10 eligible Signals, and at least 10 rejected candidates.\n`;
  await writeFile(join(outputDir, "benchmark-report.pre-audit.md"), report, "utf8");
  await writeFile(join(outputDir, "hybrid-intelligence-recommendation.json"), JSON.stringify({ run_id: run.run_id, production_routing: "HOLD", publish: false, provider_contract: { mainland: ["doubao_search", "serper"], hk_global: ["serper", "doubao_search"], people: ["serper", "exa"], tikhub: 0 }, counts: { queries: run.queries.length, candidates: run.event_candidates.length, eligible_signals: run.eligible_signals.length, verified_companies: run.verified_companies.length, deep_dive_companies: run.deep_dive_companies.length, jobs: run.jobs.length, people: run.people.length, contacts: run.contacts.length, machine_a: run.radar.leads.filter((lead) => lead.lead_pool === "A_ACTIONABLE").length, b: run.radar.leads.filter((lead) => lead.lead_pool === "B_ENRICHMENT").length }, cost: run.cost, regression: run.regression }, null, 2), "utf8");
  await writeFile(join(outputDir, "event-candidates.json"), JSON.stringify(run.event_candidates, null, 2), "utf8");
  const rejected = run.event_candidates.filter((item) => item.status !== "valid_recent_trigger").slice(0, 10);
  await writeFile(join(outputDir, "human-judgment-template.json"), JSON.stringify({ run_id: run.run_id, instructions: "人工逐条判断；不得用机器标签替代正式 Precision。", eligible_signals: run.eligible_signals.map((signal) => ({ signal_id: signal.signal_id, company_id: signal.company_id, title: signal.title, event_date: signal.event_date, judgment: null, notes: "" })), rejected_event_sample: rejected.map((event) => ({ event_id: event.event_id, title: event.title, url: event.url, machine_status: event.status, judgment: null, notes: "" })), human_approved_a: [] }, null, 2), "utf8");
  await writeFile(join(outputDir, "provider-usage.json"), JSON.stringify(run.provider_usage, null, 2), "utf8");
  console.log(JSON.stringify({ run_id: run.run_id, output_dir: outputDir, queries: run.queries.length, event_candidates: run.event_candidates.length, eligible_signals: run.eligible_signals.length, verified_companies: run.verified_companies.length, machine_a: run.radar.leads.filter((lead) => lead.lead_pool === "A_ACTIONABLE").length, b: run.radar.leads.filter((lead) => lead.lead_pool === "B_ENRICHMENT").length, production_routing: "HOLD" }, null, 2));
}

void main().catch((error) => { console.error(error); process.exitCode = 1; });
