import { createApp } from "../src/api/app";
import { createAppContext } from "../src/api/context";
import type { LLMAdapter, LLMRequest, LLMResponse } from "../src/agents/llm-adapter";
import { reviseRadarVersionWithLlm } from "../src/agents/radar-version-llm-reviser";
import { createDefaultSpec } from "../src/schema/radar-requirement-spec";
import type { RadarRevisionRequest, RadarVersionSpec } from "../src/schema/radar-version-spec";

process.env.LLM_MODE = "mock";

let pass = 0;
let fail = 0;

function check(name: string, condition: boolean, detail = "") {
  if (condition) {
    pass += 1;
    console.log(`PASS ${name}`);
  } else {
    fail += 1;
    console.error(`FAIL ${name}${detail ? `: ${detail}` : ""}`);
  }
}

function json(value: unknown): string {
  return JSON.stringify(value);
}

class FakeLlmAdapter implements LLMAdapter {
  constructor(private readonly content: string) {}

  async chat(_request: LLMRequest): Promise<LLMResponse> {
    return { content: this.content };
  }
}

function createBaseRequest(userMessage = "我不是学生，我是 OPC 创业者，优先奖金、云资源、能上架展示的比赛。"): RadarRevisionRequest {
  const spec = createDefaultSpec();
  spec.client_profile.business_type = "个人开发者";
  spec.client_profile.client_type = "个人开发者";
  spec.core_goals.primary_goal = "寻找 AI 比赛机会";
  spec.opportunity_scope.primary_opportunity_types = ["AI 比赛", "Hackathon"];
  spec.confirmation_status = {
    status: "confirmed",
    user_confirmed: true,
    confirmed_at: "2026-07-03T00:00:00.000Z",
    last_user_feedback: "",
    revision_count: 0,
  };
  const radarVersion: RadarVersionSpec = {
    version: "V1.0",
    oneSentencePositioning: "个人开发者的 AI 比赛机会雷达",
    targetUser: "个人开发者",
    businessContext: "寻找 AI 比赛、Hackathon 和开发者机会。",
    opportunityIntents: ["AI 比赛", "Hackathon"],
    highValueCriteria: ["有报名入口"],
    exclusionRules: ["排除培训广告"],
    prioritySourceArchetypes: ["official_event_site"],
    queryFamilies: [],
    scoringRules: [],
    reportTemplate: [],
    missingConfig: [],
    defaultAssumptions: [],
    revisionNotes: [],
    resultBuckets: ["direct_opportunity", "watch_signal", "reference_case", "rejected"],
  };
  spec.radar_version = radarVersion;
  return {
    previousSpec: spec,
    previousRadarVersion: radarVersion,
    userMessage,
    trigger: "requirement_correction",
    revisionMode: "llm",
  };
}

const validPayload = JSON.stringify({
  radarVersion: {
    oneSentencePositioning: "OPC 创业者的 AI Agent 参赛机会雷达",
    targetUser: "OPC 创业者 / AI 工具开发者",
    businessContext: "优先寻找能报名、能拿奖金或云资源、能展示产品的 AI Agent 开发者机会。",
    opportunityIntents: ["AI Agent 开发者挑战赛", "Hackathon", "云厂商创业扶持", "产品上架展示机会"],
    highValueCriteria: ["有官方报名入口", "有奖金或云资源", "适合非学生个人开发者", "能形成产品展示或上架"],
    exclusionRules: ["学生专属赛事", "展会资讯", "行业趋势文章"],
    prioritySourceArchetypes: ["云厂商开发者挑战赛官网", "Hackathon 平台", "AI Agent 大赛官网", "开发者社区官方公告"],
    queryFamilies: [
      {
        familyName: "AI Agent developer challenge",
        intentType: "direct_opportunity",
        sourceArchetype: "cloud developer challenge page",
        queries: [
          "AI Agent developer challenge application cloud credits",
          "AI hackathon startup founder prize application",
          "AI tool developer competition registration deadline",
        ],
        whyThisFamily: "用户要的是能报名、能拿资源、能展示产品的 AI 参赛机会。",
        resultBucket: "direct_opportunity",
      },
    ],
    defaultAssumptions: ["默认用户不是学生，按 OPC 创业者视角筛选。"],
  },
  radarDiff: {
    summary: "从个人开发者泛 AI 比赛升级为 OPC 创业者可报名 AI Agent 机会。",
    added: ["OPC 创业者视角", "AI Agent 开发者挑战赛", "云资源和上架展示"],
    removed: ["学生专属机会优先级"],
    upweighted: ["官方报名入口", "奖金或云资源", "可展示产品"],
    downweighted: ["展会资讯", "行业趋势文章"],
    assumptionChanges: ["默认用户身份为 OPC 创业者 / AI 工具开发者。"],
    queryShifts: ["加入 application、registration、deadline、cloud credits 查询方向。"],
    sourceShifts: ["云厂商开发者挑战赛官网", "Hackathon 平台"],
    highValueCriteriaChanges: ["必须能形成报名、提交或官方复核动作。"],
    exclusionChanges: ["排除学生专属赛事和纯展会资讯。"],
  },
  suggestedName: "AI Agent 参赛雷达",
  confirmationPrompt: "我已升级为 V1.1，请确认是否按这版盯一次。",
});

async function runModuleChecks() {
  const request = createBaseRequest();
  const llmResult = await reviseRadarVersionWithLlm(request, new FakeLlmAdapter(validPayload), {
    provider: "fake",
    model: "q7-c-test",
  });

  check("valid LLM output is used", llmResult.revisionSource === "llm", llmResult.revisionSource ?? "");
  check("valid LLM diagnostics do not fallback", llmResult.llmValidation?.used === true && llmResult.llmValidation.fallbackUsed === false, json(llmResult.llmValidation));
  check("LLM revision keeps version generated by local code", llmResult.radarVersion.version === "V1.1", llmResult.radarVersion.version);
  check("LLM revision updates target user", /OPC|工具开发者/.test(llmResult.radarVersion.targetUser), llmResult.radarVersion.targetUser);
  check("LLM revision updates high value criteria", /云资源|上架|报名/.test(json(llmResult.radarVersion.highValueCriteria)), json(llmResult.radarVersion.highValueCriteria));
  check("LLM revision updates exclusions", /学生|展会/.test(json(llmResult.radarVersion.exclusionRules)), json(llmResult.radarVersion.exclusionRules));
  check("LLM revision updates source archetypes", /云厂商|Hackathon|开发者/.test(json(llmResult.radarVersion.prioritySourceArchetypes)), json(llmResult.radarVersion.prioritySourceArchetypes));
  check("LLM revision updates query families", /AI Agent|application|cloud/i.test(json(llmResult.radarVersion.queryFamilies)), json(llmResult.radarVersion.queryFamilies));
  check("LLM revision writes back structured spec", /OPC|工具开发者/.test(llmResult.spec.client_profile.business_type), llmResult.spec.client_profile.business_type);
  check("LLM revision requires re-confirmation", llmResult.spec.confirmation_status?.user_confirmed === false, json(llmResult.spec.confirmation_status));
  check("LLM revision does not produce opportunity cards", !("opportunityCards" in (llmResult as any)), json(llmResult));

  const invalidResult = await reviseRadarVersionWithLlm(request, new FakeLlmAdapter("我觉得可以改好了，但这里不是 JSON"));
  check("invalid LLM output falls back", invalidResult.revisionSource === "llm_fallback", invalidResult.revisionSource ?? "");
  check("invalid LLM fallback reports error", (invalidResult.llmValidation?.errors.length ?? 0) > 0, json(invalidResult.llmValidation));
  check("invalid LLM fallback still revises deterministically", invalidResult.radarVersion.version === "V1.1", invalidResult.radarVersion.version);

  const forbiddenResult = await reviseRadarVersionWithLlm(request, new FakeLlmAdapter(JSON.stringify({
    radarVersion: { targetUser: "OPC 创业者" },
    opportunityCards: [{ title: "编造出来的比赛" }],
  })));
  check("forbidden search-result payload falls back", forbiddenResult.revisionSource === "llm_fallback", forbiddenResult.revisionSource ?? "");
  check("forbidden payload error explains result field", /机会卡|搜索结果/.test(json(forbiddenResult.llmValidation?.errors)), json(forbiddenResult.llmValidation));
}

async function runApiChecks() {
  const ctx = createAppContext();
  ctx.llmAdapter = new FakeLlmAdapter(validPayload);
  const app = createApp(ctx);
  const response = await app.request("/api/radars/revise", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(createBaseRequest()),
  });
  const body = await response.json() as { success: boolean; data?: any; error?: any };
  check("revision API accepts explicit LLM mode", response.status === 200 && body.success === true, `${response.status} ${json(body.error)}`);
  check("revision API returns LLM source", body.data?.revisionSource === "llm", body.data?.revisionSource ?? "");
  check("revision API returns draft confirmation gate", body.data?.spec?.confirmation_status?.user_confirmed === false, json(body.data?.spec?.confirmation_status));
}

runModuleChecks()
  .then(runApiChecks)
  .then(() => {
    if (fail > 0) {
      console.error(`Q.7 LLM reviser: ${pass} PASS / ${fail} FAIL`);
      process.exit(1);
    }
    console.log(`Q.7 LLM reviser: ${pass} PASS / 0 FAIL`);
  })
  .catch((err) => {
    console.error(err);
    process.exit(1);
  });
