import assert from "node:assert/strict";
import fs from "node:fs";
import { computeIchOpportunityStatus } from "../src/ich/status";
import { validateIchOpportunityFile } from "../src/ich/validation";

const audit = JSON.parse(fs.readFileSync("docs/ich/stage3-ds14-import.json", "utf8")) as { gate: string; input_count: number; eligible_count: number; imported: Array<{ slug: string; workflow: string; is_published: boolean }>; formal_store_unchanged: boolean };
assert.equal(audit.gate, "pass");
assert(audit.input_count <= 10);
assert.equal(audit.eligible_count, 1);
assert.equal(audit.imported.length, 1);
assert.equal(audit.imported[0]?.slug, "eighth-gba-cultural-creative-design-competition-2026");
assert.equal(audit.imported[0]?.workflow, "published");
assert.equal(audit.imported[0]?.is_published, true);
assert.equal(audit.formal_store_unchanged, false);
const store = JSON.parse(fs.readFileSync("data/ich-opportunities.json", "utf8"));
const validation = validateIchOpportunityFile(store);
assert.equal(validation.valid, true, validation.errors.join("; "));
const entry = store.entries.find((item: { slug: string }) => item.slug === "eighth-gba-cultural-creative-design-competition-2026");
assert(entry);
assert.equal(entry.workflow.state, "published");
assert.equal(entry.is_published, true);
assert.equal(entry.sources.filter((source: { is_primary: boolean }) => source.is_primary).length, 1);
assert.equal(entry.sources[0].url, "https://www.gbawcsjds.com/col.jsp?id=127");
assert.equal(computeIchOpportunityStatus(entry, new Date("2026-09-05T12:00:00+08:00")), "active");
const urls: string[] = store.entries.flatMap((item: { sources: Array<{ is_primary: boolean; url: string }> }) => item.sources.filter((source) => source.is_primary).map((source) => source.url.replace(/#.*$/, "").replace(/\/$/, "")));
const newUrl = "https://www.gbawcsjds.com/col.jsp?id=127";
assert.equal(urls.filter((url) => url === newUrl).length, 1, "new primary source URL must be unique");
const candidateReport = fs.readFileSync("docs/ich/candidate-verification-report.md", "utf8");
assert.match(candidateReport, /输入候选：47/);
console.log(JSON.stringify({ gate: "pass", imported: 1, slug: entry.slug, workflow: entry.workflow.state, current_status: "active", primary_url_unique: true }, null, 2));
