import { FINANCE_CSS, FINANCE_JS } from "./finance-assets";

export function renderFinancePage(pathname: string): string {
  const isLogin = pathname === "/login";
  const isPublic = process.env.FINANCE_PUBLIC_MODE === "true";
  const pageTitle = isLogin ? "管理员登录" : pageLabel(pathname);
  const body = isLogin ? `<section class="finance-card finance-login"><div class="finance-eyebrow">CHANCEPING / FINANCE</div><h2>维优猎头 BD 雷达</h2><p class="finance-muted">finance.chanceping.com 管理员入口</p><form><label>账号<input name="username" autocomplete="username" required></label><label>密码<input name="password" type="password" autocomplete="current-password" required></label><button class="finance-button" type="submit">登录工作台</button></form></section>` : `<div class="finance-shell"><aside class="finance-nav"><div class="finance-brand"><span class="finance-brand-mark">C</span><div><strong>ChancePing</strong><small>维优 BD 雷达</small></div></div><div class="finance-nav-section"><span class="finance-nav-label">工作台</span>${navLinks(pathname)}</div><div class="finance-nav-footer"><span class="finance-status-dot"></span><span>数据服务正常</span>${isPublic ? "" : `<a href="#" data-finance-logout>退出登录</a>`}</div></aside><main class="finance-main"><header class="finance-topbar"><div class="finance-breadcrumb"><span>维优猎头 BD 雷达</span><span>/</span><strong>${pageTitle}</strong></div><div class="finance-top-actions"><span class="finance-live-pill"><i></i>公开只读</span><button class="finance-icon-button" aria-label="刷新数据" data-refresh>↻</button><button class="finance-button finance-button-small" onclick="location.href='/weekly'">本周周报</button></div></header>${pathname === "/weekly" ? `<section class="finance-hero"><div><div class="finance-eyebrow">WEEKLY INTELLIGENCE</div><h1>本周值得看什么？</h1><p>把近期真实事件，变成可以行动的 BD 线索。</p></div><div class="finance-hero-week"><strong data-week-label>本周</strong><span data-updated-label>等待数据</span></div></section><section class="finance-stat-row" data-hero-stats><article><span>A 级机会</span><strong>—</strong><small>待加载</small></article><article><span>有效 Signal</span><strong>—</strong><small>待加载</small></article><article><span>Contact Gate</span><strong>—</strong><small>待加载</small></article><article><span>本周线索</span><strong>—</strong><small>待加载</small></article></section>` : `<section class="finance-page-heading"><div class="finance-eyebrow">FINANCE WORKBENCH</div><h1>${pageTitle}</h1><p>把证据、阻塞与下一步行动放在同一视野中。</p></section>`}<div class="finance-workspace"><section id="finance-live-data" class="finance-content"><div class="finance-loading"><span class="finance-spinner"></span>正在加载实时数据…</div></section>${pathname === "/weekly" ? `<aside class="finance-insight" data-insight><div class="finance-insight-head"><div><div class="finance-eyebrow">OPERATOR VIEW</div><h3>本周洞察</h3></div><span class="finance-insight-badge">LIVE</span></div><div class="finance-insight-block" data-funnel><h4>Funnel</h4><p class="finance-muted">等待本周运行数据</p></div><div class="finance-insight-block" data-blockers><h4>主要阻塞</h4><p class="finance-muted">等待数据</p></div><div class="finance-insight-block" data-quality><h4>数据质量</h4><p class="finance-muted">Evidence Gate 与成本状态会显示在这里</p></div></aside>` : ""}</div></main></div>`;
  return `<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${pageTitle}｜ChancePing Finance</title><style>${FINANCE_CSS}</style></head><body>${body}<script>${FINANCE_JS}</script></body></html>`;
}

function navLinks(active: string): string { return [["/weekly", "本周"], ["/leads/a", "A级机会"], ["/leads/b", "B级情报池"], ["/trends", "趋势"], ["/companies", "公司库"], ["/runs", "雷达运行"]].map(([href, label]) => `<a class="${active === href ? "active" : ""}" href="${href}"><span>${label}</span></a>`).join(""); }
function pageLabel(pathname: string): string { return ({ "/": "本周", "/weekly": "本周", "/leads/a": "机器 A 候选", "/leads/b": "B级情报池", "/trends": "趋势", "/companies": "公司库", "/runs": "雷达运行" } as Record<string, string>)[pathname] ?? "Finance Workbench"; }
