import { Hono, type Context } from "hono";
import { filterOpportunityV2Radar, readOpportunityV2Pool, readOpportunityV2Sources, type OpportunityV2 } from "../../opportunity-v2";
import type { OpportunityV2RouteOptions } from "./opportunity-v2";

function escapeHtml(value: unknown): string {
  return String(value ?? "").replace(/[&<>"']/gu, (char) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[char] ?? char);
}

function card(item: OpportunityV2): string {
  const deadline = item.status === "UNKNOWN_DEADLINE" ? "截止时间待确认" : new Date(item.deadline as string).toLocaleDateString("zh-CN");
  return `<article class="card"><div class="eyebrow">${escapeHtml(item.category)} · ${escapeHtml(item.region)}</div><h2>${escapeHtml(item.title)}</h2><p>${escapeHtml(item.summary)}</p><div class="meta"><span>来源：${escapeHtml(item.source_name)}</span><span>截止：${escapeHtml(deadline)}</span></div><a href="${escapeHtml(item.detail_url)}" rel="noreferrer" target="_blank">查看详情 ↗</a></article>`;
}

export function opportunityV2PagesRoutes(options: OpportunityV2RouteOptions = {}): Hono {
  const app = new Hono();
  const render = (c: Context) => {
    const sources = readOpportunityV2Sources(options.sourcesPath);
    const opportunities = filterOpportunityV2Radar(readOpportunityV2Pool(options.poolPath).opportunities, sources);
    const body = opportunities.length ? opportunities.map(card).join("") : `<div class="empty">还没有可展示的机会。请先运行 V2 聚合抓取。</div>`;
    return c.html(`<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>非遗机会雷达 V2 · ChancePing</title><style>body{margin:0;background:#f5f1e8;color:#28261f;font:15px/1.65 system-ui,sans-serif}.wrap{max-width:1120px;margin:auto;padding:28px 22px 60px}header{display:flex;justify-content:space-between;align-items:end;border-bottom:1px solid #d8cfbf;padding-bottom:18px}h1{font:36px Georgia,serif;margin:0}header p{color:#706a5f;margin:5px 0 0}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:0 28px;margin-top:12px}.card{border-bottom:1px solid #d8cfbf;padding:22px 0}.eyebrow{color:#637b6c;font-size:12px}.card h2{font:21px Georgia,serif;margin:7px 0}.card p{color:#6b655b;margin:0 0 10px}.meta{display:flex;gap:18px;color:#837b6e;font-size:12px;margin-bottom:9px}.card a{color:#31506a;text-decoration:none}.empty{margin-top:35px;padding:30px;background:#ebe4d6;color:#6b655b}@media(max-width:700px){header{display:block}.grid{display:block}h1{font-size:30px}}</style></head><body><main class="wrap"><header><div><h1>非遗机会雷达</h1><p>Source Pool → Opportunity Pool → Radar View · V2 Simple Aggregator</p></div><strong>${opportunities.length} 条当前机会</strong></header><section class="grid">${body}</section></main></body></html>`);
  };
  app.get("/admin/sources", (c) => c.html(`<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Source Manager · ChancePing</title><style>body{margin:0;background:#f5f1e8;color:#28261f;font:14px/1.5 system-ui,sans-serif}.wrap{max-width:1180px;margin:auto;padding:28px 22px 60px}h1{font:34px Georgia,serif;margin:0}header{display:flex;justify-content:space-between;align-items:end;border-bottom:1px solid #d8cfbf;padding-bottom:18px;margin-bottom:22px}header p{color:#706a5f;margin:5px 0 0}.layout{display:grid;grid-template-columns:330px 1fr;gap:24px}.panel{background:#fffaf1;border:1px solid #ded4c4;padding:18px}label{display:block;color:#6b655b;font-size:12px;margin:10px 0 4px}input,select{box-sizing:border-box;width:100%;padding:9px;border:1px solid #cfc4b3;background:#fff;color:#28261f}button{border:1px solid #8d806e;background:#31506a;color:white;padding:7px 10px;cursor:pointer;margin:2px}button.secondary{background:#fff;color:#31506a}button.danger{background:#8b493f}table{width:100%;border-collapse:collapse;background:#fffaf1}th,td{text-align:left;border-bottom:1px solid #ded4c4;padding:10px 8px;vertical-align:top}th{color:#6b655b;font-size:12px}.muted{color:#837b6e;font-size:12px}.status{font-size:12px;padding:2px 6px;border-radius:3px;background:#e5e0d4}.status.active{color:#315e45;background:#dcebdc}.status.needs_adapter{color:#875f27;background:#f3e5c3}.status.failed{color:#8b493f;background:#f3dcd7}#message{min-height:24px;color:#31506a;margin:8px 0}@media(max-width:850px){.layout{display:block}.panel{margin-bottom:20px}table{font-size:12px;display:block;overflow:auto}}</style></head><body><main class="wrap"><header><div><h1>Source Manager</h1><p>Opportunity V2 · 来源池管理</p></div><a href="/opportunity-v2">返回 Radar View</a></header><div id="message"></div><section class="layout"><form id="source-form" class="panel"><input id="source-id" type="hidden"><label for="source-name">名称</label><input id="source-name" required placeholder="某非遗市集平台"><label for="source-url">URL</label><input id="source-url" type="url" required placeholder="https://example.com/markets"><label for="source-region">地区</label><select id="source-region"><option>CN</option><option>GLOBAL</option></select><label for="source-priority">优先级</label><select id="source-priority"><option>P0</option><option>P1</option></select><label for="source-types">机会类型（逗号分隔）</label><input id="source-types" placeholder="market, open_call"><label for="source-radars">适用 Radar（逗号分隔）</label><input id="source-radars" value="ich" required><p><button type="submit">保存来源</button><button type="button" id="cancel-edit" class="secondary">清空</button></p><p class="muted">新来源保存后会立即 test；通用解析成功会自动首次抓取。</p></form><section><table><thead><tr><th>来源</th><th>地区 / 优先级</th><th>状态</th><th>最近抓取</th><th>操作</th></tr></thead><tbody id="sources-body"></tbody></table></section></section></main><script>
const apiBase='/api/opportunity-v2';
const form=document.getElementById('source-form');
const message=document.getElementById('message');
const body=document.getElementById('sources-body');
let sourceRows=[];
function esc(value){return String(value||'').replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]});}
function label(status){return {'ACTIVE':'ACTIVE','PAUSED':'已暂停','FAILED':'FAILED','NEEDS_ADAPTER':'需要适配','PENDING':'待测试','BLOCKED':'BLOCKED'}[status]||status}
function say(text){message.textContent=text||''}
async function load(){const response=await fetch(apiBase+'/sources'); const data=await response.json(); sourceRows=data.sources||[]; body.innerHTML=sourceRows.map(function(s){return '<tr><td><strong>'+esc(s.name)+'</strong><div class="muted">'+esc(s.id)+'<br>'+esc(s.url)+'</div></td><td>'+esc(s.region)+' / '+esc(s.priority)+'<br><span class="muted">'+esc((s.types||[]).join(', '))+'</span></td><td><span class="status '+esc(String(s.status).toLowerCase())+'">'+esc(label(s.status))+'</span><br><span class="muted">'+(s.enabled?'启用':'停用')+'</span></td><td class="muted">'+esc(s.last_fetch_at||'—')+'</td><td><button data-action="edit" data-id="'+esc(s.id)+'" class="secondary">编辑</button><button data-action="test" data-id="'+esc(s.id)+'" class="secondary">测试</button><button data-action="run" data-id="'+esc(s.id)+'">抓取</button><button data-action="toggle" data-id="'+esc(s.id)+'" class="secondary">'+(s.enabled?'暂停':'启用')+'</button><button data-action="delete" data-id="'+esc(s.id)+'" class="danger">停用</button></td></tr>'}).join('')}
function clearForm(){form.reset(); document.getElementById('source-id').value=''; document.getElementById('source-radars').value='ich'}
form.addEventListener('submit',async function(event){event.preventDefault(); const id=document.getElementById('source-id').value; const payload={name:document.getElementById('source-name').value,url:document.getElementById('source-url').value,region:document.getElementById('source-region').value,priority:document.getElementById('source-priority').value,types:document.getElementById('source-types').value,radars:document.getElementById('source-radars').value}; const response=await fetch(apiBase+'/sources'+(id?'/'+encodeURIComponent(id):''),{method:id?'PUT':'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)}); const data=await response.json(); say(response.ok?(id?'来源已更新':'来源已保存，已完成首次测试/抓取'):(data.error&&data.error.message)||'保存失败'); if(response.ok){clearForm();load()}});
document.getElementById('cancel-edit').addEventListener('click',clearForm);
body.addEventListener('click',async function(event){const button=event.target.closest('button[data-action]');if(!button)return;const id=button.dataset.id;const source=sourceRows.find(function(item){return item.id===id});const action=button.dataset.action;if(action==='edit'){document.getElementById('source-id').value=source.id;document.getElementById('source-name').value=source.name;document.getElementById('source-url').value=source.url;document.getElementById('source-region').value=source.region;document.getElementById('source-priority').value=source.priority;document.getElementById('source-types').value=(source.types||[]).join(', ');document.getElementById('source-radars').value=(source.radars||[]).join(', ');window.scrollTo({top:0,behavior:'smooth'});return}const endpoint=action==='test'?'/test':action==='run'?'/run':action==='toggle'?(source.enabled?'/pause':'/enable'):'';const response=await fetch(apiBase+'/sources/'+encodeURIComponent(id)+endpoint,{method:action==='delete'?'DELETE':'POST'});const data=await response.json();say(response.ok?(action==='test'?'测试完成':action==='run'?'抓取完成':action==='delete'?'来源已停用':(source.enabled?'来源已暂停':'来源已启用')):((data.error&&data.error.message)||'操作失败'));load()});
load().catch(function(){say('无法读取来源池')});
</script></body></html>`));
  app.get("/", render);
  app.get("", render);
  return app;
}
