(() => {
  const app = document.getElementById("business-app");
  const editionIds = new Set(["guangzhou", "tianhe", "shaoguan"]);
  const esc = (v) => String(v ?? "").replace(/[&<>'"]/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "'": "&#39;", '"': "&quot;" }[c]));
  const state = () => { const p = location.pathname.split("/").filter(Boolean); return { edition: editionIds.has(p[0]) ? p[0] : "guangzhou", page: p[1] || "home", slug: p[2] || "" }; };
  const status = (i) => ({ current: "当前有效", closing_soon: "即将截止", rolling: "长期/滚动", historical: "已结束" })[i.lifecycleStatus] || "待核验";
  const categoryIcon = (category) => ({ policy: "▤", procurement: "🛒", funding: "¥", event: "✦", cooperation: "↗" }[category] || "•");
  const fitScore = (item) => ({ high: 85, medium: 78, low: 62 }[item.recommendationLevel] || 78);
  const empty = (t, p) => `<section class="business-empty"><span>NO CURRENT DATA</span><h2>${esc(t)}</h2><p>${esc(p)}</p></section>`;
  function header(common, edition, page, content) {
    document.title = edition.seo.title;
    const links = [["首页", edition.route, "home"], ["全部机会", `${edition.route}/opportunities`, "opportunities"], ["信息来源", `${edition.route}/sources`, "sources"], ["关于雷达", `${edition.route}/about`, "about"]];
    const editionLinks = [{ id: "guangzhou", name: "广州" }, { id: "tianhe", name: "天河" }, { id: "shaoguan", name: "韶关" }];
    return `<header class="business-header"><a class="business-brand" href="${edition.route}"><span class="business-brand-mark" aria-hidden="true">C</span><span>ChancePing <b>Business Radar</b></span><small>${esc(edition.shortName)}</small></a><nav class="business-edition-switcher" aria-label="城市版本">${editionLinks.map((item) => `<a class="${edition.id === item.id ? "is-active" : ""}" href="/${item.id}">${item.name}</a>`).join("")}</nav><nav class="business-nav">${links.slice(0, 1).map(([n, href, id]) => `<a class="${page === id ? "is-active" : ""}" href="${href}">${n}</a>`).join("")}<a class="${page === "opportunities" ? "is-active" : ""}" href="${edition.route}/opportunities">全部机会</a><a href="${edition.route}/sources">信息来源</a></nav><nav class="business-utility" aria-label="账户工具"><a href="${edition.route}/opportunities?view=saved"><span aria-hidden="true">♡</span> 我的关注</a><a href="${edition.route}/about"><span aria-hidden="true">♧</span> 消息</a><a class="business-main-link" href="https://www.chanceping.com/">企业中心⌄</a></nav></header><main class="business-shell business-shell-${page}">${content}</main><footer class="business-footer"><p>${esc(common.disclaimer)}</p><small>${esc(edition.footerNote)} · 数据以官方原文为准</small></footer>`;
  }
  function card(item, edition) { const deadline = item.deadline ? new Date(item.deadline).toLocaleDateString("zh-CN") : "截止未公开"; return `<article class="business-card business-opportunity-card"><div class="business-card-icon business-icon-${esc(item.category)}">${categoryIcon(item.category)}</div><div class="business-card-main"><div class="business-card-meta"><span class="business-category-label">${esc(item.categoryLabel)}</span><span class="business-status">${status(item)}</span></div><h2>${esc(item.title)}</h2><p class="business-card-summary">${esc(item.summary)}</p><dl class="business-card-facts"><div><dt>适合企业</dt><dd>${esc(item.eligibilitySummary || "符合公告要求的企业或申报主体")}</dd></div><div><dt>来源</dt><dd>${esc(item.sourceName || "官方来源")} · <strong>${esc(item.verificationLabel)}</strong></dd></div></dl></div><div class="business-card-side"><strong class="business-fit">${fitScore(item)}%</strong><span>适配度</span><span class="business-deadline">截止 ${esc(deadline)}</span><a class="business-card-link" href="${edition.route}/opportunities/${encodeURIComponent(item.slug)}">查看详情 →</a><button class="business-save" type="button" aria-label="收藏机会">♡</button></div></article>`; }
  function list(edition, data) {
    const options = data.categories.map((c) => `<option value="${c.id}">${esc(c.label)}</option>`).join("");
    return `<section class="business-section"><div class="business-section-heading"><div><p class="business-kicker">OPPORTUNITY DIRECTORY</p><h1>全部机会</h1></div><span id="business-total">${data.total} 条记录</span><div class="business-view-toggle" role="group" aria-label="视图切换"><button type="button" data-view="cards">卡片</button><button type="button" class="is-active" data-view="list">列表</button></div></div><form id="business-filters" class="business-filters"><input name="q" placeholder="搜索标题、机构或关键词"><select name="category"><option value="all">全部分类</option>${options}</select><select name="status"><option value="all">全部状态</option><option value="current">当前有效</option><option value="historical">已结束</option></select><select name="audience"><option value="">全部对象</option><option value="enterprise">企业</option><option value="supplier">供应商</option><option value="institution">机构</option></select><label>截止起 <input type="date" name="deadline_from"></label><label>截止至 <input type="date" name="deadline_to"></label><select name="sort"><option value="updated">最近更新</option><option value="deadline">截止时间</option><option value="recommendation">推荐优先</option></select><button>筛选</button></form><div id="business-results" class="business-list-view">${data.items.length ? data.items.map((i) => card(i, edition)).join("") : empty("未找到匹配记录", "可以调整搜索词或筛选条件。")}</div></section>`;
  }
  function detail(edition, item) { return `<article class="business-detail business-editorial-detail"><p class="business-kicker">${esc(item.categoryLabel)} · ${status(item)}</p><h1>${esc(item.title)}</h1><p class="business-detail-deck">${esc(item.summary)}</p><div class="business-detail-lead"><span>本周值得跟进</span><strong>${esc(item.verificationLabel)}</strong><em>${item.deadline ? `截止 ${esc(new Date(item.deadline).toLocaleDateString("zh-CN"))}` : "截止未公开"}</em></div><div class="business-detail-grid"><section><h2>官方信息</h2><p><strong>主办/采购单位：</strong>${esc(item.organizer)}</p><p><strong>来源：</strong>${esc(item.sourceName)}</p><p><strong>核验：</strong>${esc(item.verificationLabel)}</p><a class="business-button business-button-dark" href="${esc(item.officialUrl)}" target="_blank" rel="noopener noreferrer">查看官方通知</a><p class="business-verification-note">核验说明：${esc(item.verificationNotes)}</p></section><section><h2>为什么值得关注</h2><ul>${item.recommendationReasons.map((x) => `<li>${esc(x)}</li>`).join("")}</ul><h2>适合条件</h2><p>${esc(item.eligibilitySummary)}</p><h3>申报/参与要求</h3><ul>${(item.eligibilityRequirements || []).map((x) => `<li>${esc(x)}</li>`).join("")}</ul><h3>支持或收益</h3><p>${esc(item.rewardSummary || "以官方通知为准")}</p><h2>风险与下一步</h2><ul>${item.risks.map((x) => `<li>${esc(x)}</li>`).join("")}</ul><ol>${item.nextActions.map((x) => `<li>${esc(x)}</li>`).join("")}</ol></section></div><a href="${edition.route}/opportunities">返回全部机会</a></article>`; }
  async function fetchList(edition, extra = "") { const r = await fetch(`/api/business/opportunities?edition=${edition}${extra}`); const p = await r.json(); if (!r.ok || !p.success) throw new Error(); return p.data; }
  async function boot() {
    const s = state();
    try {
      const initialQuery = new URLSearchParams(location.search); const initialStatus = initialQuery.get("status") || "current"; initialQuery.delete("status"); const initialFilters = initialQuery.toString();
      const [cr, data] = await Promise.all([fetch(`/api/business/editions/${s.edition}`), fetchList(s.edition, `&status=${initialStatus}&diverse=1${initialFilters ? `&${initialFilters}` : ""}`)]); const cp = await cr.json(); if (!cr.ok || !cp.success) throw new Error(); const { common, edition } = cp.data;
      let content;
      if (s.page === "home") content = `<section class="business-hero business-hero-reference"><p class="business-kicker">CITY BUSINESS RADAR</p><h1>为企业找到下一步</h1><p class="business-lead">汇聚权威信息，助力企业把握城市机会</p><form class="business-hero-search" action="${edition.route}/opportunities"><span class="business-search-icon" aria-hidden="true">⌕</span><input name="q" placeholder="搜索政策、采购、展会与资金机会" aria-label="搜索机会"><button class="business-button" type="submit">搜索</button></form><div class="business-hot-searches"><span>热门搜索：</span><a href="${edition.route}/opportunities?q=高新技术企业认定">高新技术企业认定</a><a href="${edition.route}/opportunities?q=专精特新">专精特新</a><a href="${edition.route}/opportunities?q=数字化转型">数字化转型</a><a href="${edition.route}/opportunities?q=绿色低碳">绿色低碳</a><a href="${edition.route}/opportunities?q=设备采购">设备采购</a></div></section><section class="business-profile-demo"><div><p class="business-kicker">DEMO PROFILE</p><h2>先告诉我们你想关注什么</h2><p>用一个轻量画像，生成首批 20 条匹配机会；不需要注册即可预览。</p></div><form id="business-profile-form"><input name="keywords" placeholder="关键词，如：创新、采购" value="创新"><input name="industries" placeholder="行业，如：科技" value="科技"><button class="business-button" type="submit">生成我的机会</button></form><div id="business-profile-results" aria-live="polite"></div></section><section class="business-reference-results"><aside class="business-reference-filters"><h2>精准筛选</h2><fieldset><legend>机会类型</legend><label><input type="checkbox" checked> 政策支持</label><label><input type="checkbox" checked> 政府采购</label><label><input type="checkbox" checked> 资金资助</label><label><input type="checkbox"> 展会活动</label></fieldset><label>行业领域<select><option>全部行业</option></select></label><label>企业标签<select><option>请选择企业标签</option></select></label><fieldset><legend>发布时间</legend><label><input type="radio" name="time" checked> 近 30 天</label><label><input type="radio" name="time"> 近 90 天</label><label><input type="radio" name="time"> 自定义时间</label></fieldset><button type="button" class="business-reset">重置筛选</button></aside><section class="business-reference-list"><div class="business-section-heading"><div><h2>为您推荐的机会</h2><p>基于您的企业信息与关注偏好智能推荐</p></div><span>${data.total} 条机会</span><select aria-label="排序"><option>推荐排序</option><option>截止时间</option></select></div><div class="business-list-view">${data.items.slice(0, 3).map((i) => card(i, edition)).join("") || empty("暂无可公开展示的机会", "当前没有符合条件的公开机会记录。")}</div><a class="business-more-link" href="${edition.route}/opportunities">查看更多机会 →</a></section></section>`;
      else if (s.page === "opportunities" && !s.slug) content = list(edition, data);
      else if (s.page === "opportunities") { const r = await fetch(`/api/business/opportunities/${encodeURIComponent(s.slug)}?edition=${edition.id}`); const p = await r.json(); content = r.ok && p.success ? detail(edition, p.data) : empty("机会不存在", "该机会不存在或不适用于当前地区版本。"); }
      else if (s.page === "sources") { const r = await fetch(`/api/business/sources?edition=${edition.id}`); const p = await r.json(); const sources = r.ok && p.success ? p.data.items : []; content = `<section class="business-section"><h1>信息来源</h1>${sources.length ? sources.map((source) => `<article class="business-copy"><h2>${esc(source.name)}</h2><p>${esc(source.coverage)} · ${source.refreshCadence === "weekly" ? "每周巡检" : "每三天巡检"}</p><p>${esc(source.admissionPolicy)}</p><a href="${esc(source.officialUrl)}" target="_blank" rel="noopener noreferrer">打开官方来源</a></article>`).join("") : empty("尚无公开来源", "来源接入后将显示其核验状态和官方入口。")}</section>`; }
      else if (s.page === "about") content = `<section class="business-copy"><h1>${esc(edition.name)}</h1><p>${esc(edition.subheadline)}</p><p>${esc(common.disclaimer)}</p></section>`;
      else content = empty("404 页面不存在", "请从当前地区版本的导航继续浏览。");
      app.innerHTML = header(common, edition, s.page, content);
      const form = document.getElementById("business-filters"); if (form) form.addEventListener("submit", async (e) => { e.preventDefault(); const target = document.getElementById("business-results"); target.innerHTML = "<p>正在筛选…</p>"; const d = await fetchList(edition.id, `&diverse=1&${new URLSearchParams(new FormData(form)).toString()}`); document.getElementById("business-total").textContent = `${d.total} 条记录`; target.innerHTML = d.items.length ? d.items.map((i) => card(i, edition)).join("") : empty("未找到匹配记录", "可以调整搜索词或筛选条件。"); });
      document.querySelectorAll(".business-view-toggle button").forEach((button) => button.addEventListener("click", () => { document.querySelectorAll(".business-view-toggle button").forEach((b) => b.classList.remove("is-active")); button.classList.add("is-active"); const results = document.getElementById("business-results"); results.classList.toggle("business-list-view", button.dataset.view === "list"); }));
      const profileForm = document.getElementById("business-profile-form"); if (profileForm) profileForm.addEventListener("submit", async (e) => { e.preventDefault(); const result = document.getElementById("business-profile-results"); result.innerHTML = "<p>正在生成匹配…</p>"; const form = new FormData(profileForm); const r = await fetch(`/api/business/matches?edition=${edition.id}`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ keywords: String(form.get("keywords") || "").split(/[，,\s]+/).filter(Boolean), industries: String(form.get("industries") || "").split(/[，,\s]+/).filter(Boolean), regions: [edition.shortName] }) }); const p = await r.json(); result.innerHTML = r.ok && p.success ? `<p class="business-profile-gate">${p.data.gate.reason}</p><div class="business-profile-match-list">${p.data.items.slice(0, 3).map((i) => `<a href="${edition.route}/opportunities/${encodeURIComponent(i.slug)}"><strong>${esc(i.fitScore)}% · ${esc(i.title)}</strong><span>${esc(i.fitReasons[0])}</span></a>`).join("")}</div>` : "<p>匹配暂不可用，请稍后重试。</p>"; });
    } catch { app.innerHTML = `<section class="business-error"><h1>页面暂时无法加载</h1><p>机会数据或地区配置读取失败，请稍后重试。</p></section>`; }
  }
  boot();
})();
